set
	session_replication_role = replica;

-- generated by dump-new-seeds 2026-05-08T10:37:21.560Z
--
-- phrase_request (8 rows)
--
insert into
	"public"."phrase_request" ("id", "created_at", "requester_uid", "lang", "prompt", "upvote_count", "deleted", "updated_at")
values
	(
		'26fc0561-2b17-4663-a017-b88257702e25',
		now() - interval '10 days',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'ibo',
		'I see a cab and driver waiting on the road and I want to ask them if they''re available to take me someplace, how do I say this? "Are you available for hire?" "Can you take me?" etc',
		0,
		false,
		now() - interval '2 hours'
	),
	(
		'bc2e2811-1a9b-4131-981d-f2d7d7b26411',
		now() - interval '5 days',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		'How do I say "This is one of my favourite foods / I know and love this dish" like I''m being a little casual but someone is saying "oh should I get you something else?" and I''m saying "no I love this food! don''t worry, I''m just taking a minute" kind of like that.',
		0,
		false,
		now() - interval '2 hours'
	),
	(
		'e0d3a74e-4fe7-43c0-aa35-d05c83929986',
		now() - interval '3 days',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'hin',
		'How do I say "I''d like a cheeseburger?"',
		0,
		false,
		now() - interval '2 hours'
	),
	(
		'e40e53ce-0b24-4b5d-9cf4-5c1ac16d4f96',
		now() - interval '2 days',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'kan',
		'How do I order a dosa and a coffee?',
		0,
		false,
		now() - interval '2 hours'
	),
	(
		'3f8c9e2a-1234-4567-89ab-cdef01234567',
		now() - interval '8 days',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		'I''m learning to cook Indian food and need phrases for common ingredients. How do I ask for tomatoes, onions, garlic, ginger, and spices at the market?',
		2,
		false,
		now() - interval '2 hours'
	),
	(
		'4a9d0f3b-2345-5678-90bc-def012345678',
		now() - interval '6 days',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'kan',
		'How do I ask where the bathroom is in Kannada? Also need phrases for "excuse me" and "thank you".',
		1,
		false,
		now() - interval '2 hours'
	),
	(
		'5b0e1a4c-3456-4789-a1cd-ef0123456789',
		now() - interval '4 days',
		'7ad846a9-d55b-4035-8be2-dbcc70074f74',
		'hin',
		'What are some polite ways to decline food when someone offers? I don''t want to seem rude but I''m full.',
		3,
		false,
		now() - interval '2 hours'
	),
	(
		'6c1f2a5d-4567-4890-a2de-f01234567890',
		now() - interval '32 hours',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'kan',
		'Need help with directions in Kannada - left, right, straight, turn, stop.',
		0,
		false,
		now() - interval '2 hours'
	);

--
-- phrase (136 rows)
--
insert into
	"public"."phrase" ("text", "id", "added_by", "lang", "created_at", "text_script", "only_reverse", "archived")
values
	(
		'Amele',
		'b9e3edac-de8b-4796-b436-a0cded08d2ae',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'kan',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'edhu, idhu, adhu, adhunga',
		'93d5d050-e9af-4652-9c76-9dc2a232640a',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'test',
		'2fbae84f-5b1d-43c2-8927-ef4d41c7e794',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'teen logue',
		'5f7ce03f-f6a1-48cf-bb59-6265faf2ea98',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Sir map location pe aajaiye?',
		'235ce61c-be21-4697-815d-d5aa1a4ff121',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Aap log theek hain?',
		'f1f5234e-0426-44f5-a007-b67329a70a81',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'kuch nahi',
		'170f5fd4-58f8-4b05-aba4-23522f35800f',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'aur kuch?',
		'90108f59-7968-457f-9744-2e3b44e980dd',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'barish ho rahi hai',
		'9a2bc2c8-7d7a-4ddd-8eed-2812bbf73471',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'barish nahi ho rahi hai',
		'5b5cc7ec-702e-4dc1-a568-0dcc660c25bb',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'nahi',
		'f878e60f-9647-4728-a368-fc8681b0acbb',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'onnu, rendu, moonu, naalu, anju, aaru, yaelu, ettu, onbathu, pathtu',
		'295fbba3-892c-43f9-84ba-85cf15fd28a5',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		true,
		false
	),
	(
		'yallo',
		'06e117d1-1b43-4047-996f-a298aad53823',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'test',
		'9e2fef5c-d144-4ea9-9b31-0bd4cefb7ee8',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'test',
		'a8fbdb84-24bf-456e-836c-b355355caa45',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'test',
		'7f412edd-af7c-486e-a35f-3b2a7803efc9',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'haanji',
		'1395ae94-46d9-4a54-92f5-fb8b76db896b',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'signal se left',
		'4d3207d1-a0bf-4504-831e-bfadb834d315',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'aur kuch batao',
		'ded8028a-493f-438f-8b72-316c769a66b9',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'kyuki',
		'e060237f-1744-427a-8e8e-53da29582d35',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'ye kya hai?',
		'c412f03e-a014-4aaa-b0e8-0e1a58f5c6e8',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'kya hua',
		'cc3847f3-b151-401e-80c9-4aef221c54b5',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'kya ho raha hai?',
		'f6b69f3b-09b9-41a7-a9f2-255da0697015',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'bas',
		'7e01d5e8-d3ab-4cc1-8e7a-b5861f1742cd',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'thodisi dhoop hai aaj!',
		'a8d4b1f5-bdf1-4aa2-b04c-bdb8b35b27b9',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'ho gaya aajka',
		'c3d00086-6d8c-431d-b2a0-df5757457a5e',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'kitna?',
		'8167b776-fc93-4e3f-b06e-5fa5818f2d3b',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Sunlo',
		'78057374-cf85-4940-91d1-7d04c156abfb',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'dhat',
		'80b03361-25d1-434b-8935-4a2a762d2353',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'madarchod',
		'43a760da-65af-400e-b3f0-fbed7a6b338e',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Kahan Ja Rahey Ho?',
		'83daad8e-f64f-4e8d-81f7-63aedd829c11',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Patta hai',
		'903817a7-168a-4b99-87a1-79b3e3e14d84',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Hum puchhengey',
		'ee0fb561-8e07-413b-ac5c-65ec7041c17d',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'kya chal raha hai?',
		'fae20b24-42dc-4b9e-aebc-22afcdfc4689',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'aapka naam kya hai?',
		'1d44afd2-1274-47ec-8107-36bd09861c3d',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'tumhara naam kya hai?',
		'fdd62764-2438-42bb-af7f-9eb378082899',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'kya khana khaya aapne?',
		'184170d9-3717-427e-b347-35533ea52a02',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'suno iski baat',
		'ca8af1e7-304a-4aef-a22e-26d9376b6313',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'chalta hai?',
		'0823546b-d240-4f14-9d51-8dfae5fcddc3',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'chalo',
		'48edc28c-1530-4549-b48c-f678033a6892',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'chale?',
		'24746d12-8a65-47e7-97c5-87c828585db6',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'main tum se pyaar karta hoon',
		'52851577-c8ba-4254-9c74-6edd310d6971',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Polama',
		'fd535752-d602-4ab8-8656-9e11692f30fc',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'main aah raha hoon',
		'd4b66bd6-52fc-438d-afc5-3d35be9995c2',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'main ja raha hoon',
		'46ed187a-c132-4781-822f-ebb056ddf960',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'aap kaise ho?',
		'48fe0624-f586-4812-a1a5-33c634995671',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'main theek hoon',
		'7dd33e23-2b6d-4b1f-bc8c-1da690d14bfb',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'namaste',
		'0e33be07-6d4a-4c99-8282-921038188cbf',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'eik, do, teen, chaar, paanch, che, saht, aht, no, das',
		'8133abe3-f908-445a-b8ae-6f01db3c18d7',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'kyu?',
		'267acd7c-65f2-4aad-bf5c-58e01c0f69f8',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Main aur kha nahi sakta hoon',
		'1174699b-deac-480a-94af-555018da33fb',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Chaep',
		'14fd9a81-be8c-44b2-a8f7-8a2bf5c9c8e6',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Kal kaafi fun ho gaya ta',
		'f7454ec3-5673-4858-a2f9-65925083ecbf',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Main vo Kar sakta hoon',
		'0fd8b810-237a-4a38-a972-2d26706854ce',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Jo bhi chahiye order karo',
		'1b6c63dd-177f-411e-8f87-bf2b3fe7c927',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'rehene do',
		'e24dd614-0033-4c9c-a72a-475f96dcfca6',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'jaane do',
		'd40c50fd-fd7b-4c47-af68-c85ef6879ac9',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Yennaku avalova Thamil theriyadhu',
		'12536684-0b35-4aff-80cd-f4ce56c866b6',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Rassi jal gayi, bal nahi gaya',
		'b53afc7f-1349-4f28-aafb-3f471009dd97',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'essa bhi kuch hota hai?',
		'7b396c7b-18c4-4e58-97a0-bc4687e67427',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Sirf ek',
		'4c55ff26-b29e-48ce-8b72-0c28cd37d0c9',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Yeh bata de',
		'de1df463-8186-4748-9557-0de18c1a16ef',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Woh bata de',
		'ae43221d-6be8-468c-9af8-71bbab95c1ec',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Kya main boloonga?',
		'ee043244-9de8-4419-aee8-8ba2f3f5edcc',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Kya main bolun?',
		'bbe138a2-1bec-44a0-afb5-679ecc0b2214',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Din, hafta, mahina, sal',
		'f45c7d8a-acbe-42e0-8308-b2207c07eec1',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Tumhe yadh hai?',
		'ffc9e2ca-7c33-4c6f-a64a-9a8d67fe2e30',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Bhul gaya',
		'37dd6e13-d915-4c41-8767-17cdd74beb96',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'main ne 200 rupees bola ta',
		'a9b7300d-5599-42f0-b573-8c5a54f0f299',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'koi na',
		'222e15d2-e94d-4369-912e-89186e222863',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'idhar ya udhar',
		'f83954c3-864d-46c7-a4b8-d996bd5cb517',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'idhar ya udhar',
		'21ed1ee9-af6f-46e1-8f7e-7669b96db0ae',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'idhar ya udhar',
		'c6726b7d-d1b6-4e32-802f-c2352889d1fc',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'idhar ya udhar',
		'a925dd57-384c-44c2-8c8f-67ad05a05819',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'idhar ya udhar',
		'f54f8a2a-dce8-401d-badf-b3d4ab36809f',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'idhar ya udhar',
		'aa9f28b1-3481-40dd-a926-946ed4048f1a',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'idhar ya udhar',
		'469e1199-82e3-46da-8da7-c9ae60efca41',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'idhar ya udhar',
		'24971c85-e336-4af4-821e-74bc6f9c9099',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'idhar ya udhar',
		'1989b6d7-2904-4e4d-88de-a0bc7f0ecaa0',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'asdf',
		'6dacfd10-fb5f-4b48-a21b-43b13b591d03',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'idhar ya udhar',
		'70182dec-e235-4aa5-9364-5d1c7c91fa59',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Adengappa',
		'4677f15a-1cd9-40a3-876c-30662c5eec3f',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Teriya ille',
		'163d7f57-a76f-4e5b-9346-1de5cfeba7d8',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'chitti, periamma',
		'1f6bac22-b32a-4b77-9857-d2de02b538de',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'hallo',
		'76402538-688d-4757-bdd9-c07d09c124dc',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Idhar ya udhar?',
		'2b15b306-52f0-4493-bab5-634287a7fb47',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Idhar ya udhar',
		'3d0e57a6-eaf2-4eab-922d-f2055c611418',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'idhar ya udhar',
		'13a8cb15-f575-461a-afe3-bbca427a7c0b',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'idhar ya udhar',
		'5c5c5c0c-324a-42eb-8e06-461ee63c4b5f',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'idhar ya udhar',
		'23fbf5e9-fabe-4da0-9175-0b0f462216af',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'idhar ya udhar',
		'cbcff06c-4a47-449b-a1c3-c37b4443df5b',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'idhar ya udhar',
		'0972c5a6-464a-4193-9f0d-b2fbcf0bd71d',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'idhar ya udhar',
		'909ae4d6-bd02-46b1-a9f1-93469ea9ea94',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'hindi phrase',
		'7ae6b46c-c7c8-480c-a242-0655a34b6aec',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'laet ja',
		'c8cca0b1-7176-4418-ba82-279e97278a1b',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Maria de illa',
		'c1cc1a36-1b77-41bf-9a05-6e7914d256e2',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'kan',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'theek hai',
		'bf1cee96-86f2-44e9-97e3-59897dd864ed',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'accha hai',
		'215b33a1-9277-4c19-ae85-788892019566',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'ho gaya',
		'2a710c3c-7f9f-462b-86df-41d08563c809',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'kya hai?',
		'2bf98841-7cde-493c-86b6-a47889303b65',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'khatham ho gaya',
		'2ed5fa12-40d1-4d22-88ee-5e52d373e3aa',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Sab theek?',
		'1a28066b-bfc7-4be8-ac51-87226527820e',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Haina?',
		'c952444c-c89f-4105-8e75-cd5156e6d925',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Main bimar hoon',
		'1269f7f0-d675-4f01-b378-7671b80b1fa7',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Vandu tea kudhi ',
		'b7247f31-3758-47ea-bdf8-1c2a7ff161ed',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'kan',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'main thaki hui hoon ',
		'1c1aaa6d-f49e-4dca-88a4-b2f417b352a5',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'mujhe bhookh lag rahi hai',
		'788c7250-6ce2-445d-85a0-1d13751d64bd',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'yār, enna, en, eppolutu, enge, eppati',
		'24a18665-a343-4960-99fc-7e5ed54accb0',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		true,
		false
	),
	(
		'Patthu, iruvathu, mubbathu, naapathu, aimbathu, arupathu, ezhupadhu, enpadhu, Tonoothu, noothu',
		'ed70550e-da8a-44dc-8bfd-69965375b7f9',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		true,
		false
	),
	(
		'test 1 ',
		'a76bcc62-879a-4da5-95c1-de11d64bac91',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'idhu irukē?',
		'fa26ba78-a7a3-49f8-8516-034424477dec',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'epudi irukē?',
		'c3c81fa4-9c63-4569-b9b6-9c931ee3154f',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'epadi irukeenge?',
		'b2736292-1137-41db-a453-ad203726d8c5',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'epadi irukeenge?',
		'4b7b3741-16ce-4ce8-a9b8-70556451a8e5',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'epadi irukeenge?',
		'ddd650c2-00e9-43f1-8624-5a97282087aa',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'epadi irukeenge?',
		'7aac8e8f-4de1-41a0-b910-a2c9b80e47f9',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'epadi irukeenge',
		'de2ea356-e63d-46f7-8123-2aa9370673ec',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'epadi irukeenge?',
		'a2777e37-b02e-4d8b-9a39-1a9ad56af4f2',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'comment ca va',
		'a875f6e4-a8cc-4f68-baf3-ca2aea273568',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'comment ca va',
		'44bcd224-b4b3-46ce-b260-2136712b0907',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'comment ca va',
		'a00febfd-e6d6-40bc-a3b8-e31563410db8',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'comment ca va',
		'c5c8cf9b-bf1a-4d4a-aff6-21b8dc86fcc9',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'comment ca va',
		'49066ea2-e608-42ab-8817-1f20b0eada03',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'comment ca va',
		'97f2f7cb-a1c5-4bb1-a93b-d475fa96ae68',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'[mujhe] ek cheeseburger chahiye',
		'dd039576-9798-422f-b946-ffe86e0d8324',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'hin',
		now() - interval '2 days',
		null,
		false,
		false
	),
	(
		'Ondu coffee mattu dosa kodhi',
		'b0fbbe1d-705e-4d93-a231-ac55263fcfee',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'kan',
		now() - interval '26 hours',
		null,
		false,
		false
	),
	(
		'Nimage hEgidE?',
		'aa110001-1111-4aaa-bbbb-cccccccccccc',
		'a32f65e7-a496-4afc-abd3-798d8e6d9ec5',
		'kan',
		now() - interval '25 days',
		null,
		false,
		false
	),
	(
		'Dhanyavadagalu',
		'aa110002-2222-4aaa-bbbb-cccccccccccc',
		'a32f65e7-a496-4afc-abd3-798d8e6d9ec5',
		'kan',
		now() - interval '25 days',
		null,
		false,
		false
	),
	(
		'Nanu Kannada kaliyuttiddene',
		'aa110003-3333-4aaa-bbbb-cccccccccccc',
		'a32f65e7-a496-4afc-abd3-798d8e6d9ec5',
		'kan',
		now() - interval '24 days',
		null,
		false,
		false
	),
	(
		'Idhu eshtu?',
		'aa110004-4444-4aaa-bbbb-cccccccccccc',
		'a32f65e7-a496-4afc-abd3-798d8e6d9ec5',
		'kan',
		now() - interval '24 days',
		null,
		false,
		false
	),
	(
		'Shauchalaya elli?',
		'aa110005-5555-4aaa-bbbb-cccccccccccc',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'kan',
		now() - interval '20 days',
		null,
		false,
		false
	),
	(
		'Nanu swalpa Kannada matadtini',
		'aa110006-6666-4aaa-bbbb-cccccccccccc',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'kan',
		now() - interval '20 days',
		null,
		false,
		false
	),
	(
		'Hosa varsha shubhashayagalu',
		'aa110007-7777-4aaa-bbbb-cccccccccccc',
		'a32f65e7-a496-4afc-abd3-798d8e6d9ec5',
		'kan',
		now() - interval '18 days',
		null,
		false,
		false
	),
	(
		'Oota aayitha?',
		'aa110008-8888-4aaa-bbbb-cccccccccccc',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'kan',
		now() - interval '15 days',
		null,
		false,
		false
	),
	(
		'Ondu tea kodhe',
		'884b7e6d-5aa0-49ba-be42-e26d37e20f12',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'kan',
		now() - interval '22 hours',
		null,
		false,
		false
	),
	(
		'Nānu eraḍu dōse tinde',
		'223330a3-9bba-496f-aa45-1007d462e676',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'kan',
		now() - interval '22 hours',
		null,
		false,
		false
	);

--
-- phrase_playlist (11 rows)
--
insert into
	"public"."phrase_playlist" (
		"id",
		"uid",
		"title",
		"description",
		"href",
		"created_at",
		"lang",
		"upvote_count",
		"deleted",
		"updated_at",
		"cover_image_path"
	)
values
	(
		'a1b2c3d4-1111-4222-a333-444444444444',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'Essential Hindi Greetings',
		'Common greetings and polite phrases for everyday conversations in Hindi',
		null,
		now() - interval '15 days',
		'hin',
		12,
		false,
		now() - interval '2 hours',
		null
	),
	(
		'b2c3d4e5-2222-4333-a444-555555555555',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'Hindi Questions',
		'Useful question phrases to help you get information',
		null,
		now() - interval '12 days',
		'hin',
		8,
		false,
		now() - interval '2 hours',
		null
	),
	(
		'c3d4e5f6-3333-4444-a555-666666666666',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'Basic Kannada Phrases',
		'Starter phrases for Kannada learners',
		null,
		now() - interval '10 days',
		'kan',
		5,
		false,
		now() - interval '2 hours',
		null
	),
	(
		'd4e5f6a7-4444-4555-a666-777777777777',
		'7ad846a9-d55b-4035-8be2-dbcc70074f74',
		'Hindi Numbers and Counting',
		'Learn to count in Hindi from 1 to 10',
		null,
		now() - interval '7 days',
		'hin',
		15,
		false,
		now() - interval '2 hours',
		null
	),
	(
		'e5f6a7b8-5555-4666-a777-888888888888',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'Kannada Food & Dining',
		'Order food and drinks in Kannada restaurants',
		null,
		now() - interval '5 days',
		'kan',
		9,
		false,
		now() - interval '2 hours',
		null
	),
	(
		'f6a7b8c9-6666-7777-8888-999999999999',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'Hindi Travel Phrases',
		'Essential phrases for getting around in Hindi-speaking areas',
		null,
		now() - interval '3 days',
		'hin',
		6,
		false,
		now() - interval '2 hours',
		null
	),
	(
		'aa220001-1111-4aaa-bbbb-dddddddddddd',
		'a32f65e7-a496-4afc-abd3-798d8e6d9ec5',
		'Kannada Survival Kit',
		'The bare minimum phrases you need to get by in Karnataka',
		null,
		now() - interval '14 days',
		'kan',
		7,
		false,
		now() - interval '2 hours',
		null
	),
	(
		'aa220002-2222-4aaa-bbbb-dddddddddddd',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'Hindi Expressions & Feelings',
		'Common ways to express emotions and reactions in Hindi',
		null,
		now() - interval '11 days',
		'hin',
		4,
		false,
		now() - interval '2 hours',
		null
	),
	(
		'aa220003-3333-4aaa-bbbb-dddddddddddd',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'Kannada at the Market',
		'Phrases for shopping, bargaining, and buying groceries in Kannada',
		null,
		now() - interval '9 days',
		'kan',
		11,
		false,
		now() - interval '2 hours',
		null
	),
	(
		'aa220004-4444-4aaa-bbbb-dddddddddddd',
		'7ad846a9-d55b-4035-8be2-dbcc70074f74',
		'Hindi Daily Conversations',
		'Everyday small-talk phrases that come up constantly',
		null,
		now() - interval '6 days',
		'hin',
		3,
		false,
		now() - interval '2 hours',
		null
	),
	(
		'05ddae3c-a241-43c2-b3e1-228a56867097',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'Kannada Gothilla Pod: Counting Numbers, July 2021',
		'Kannada Gothilla Podcast episode on the counting numbers! How to count, the overall counting "system" in Kannada, and some phrases where you''d use the numbers in daily life.',
		'https://open.spotify.com/episode/7camUCOPmHHa1Mu4lSdI3L',
		now() - interval '22 hours',
		'kan',
		0,
		false,
		now() - interval '2 hours',
		null
	);

--
-- chat_message (5 rows)
--
insert into
	"public"."chat_message" (
		"id",
		"created_at",
		"sender_uid",
		"recipient_uid",
		"message_type",
		"phrase_id",
		"related_message_id",
		"content",
		"lang",
		"request_id",
		"playlist_id",
		"read_at"
	)
values
	(
		'9d88502f-9769-4e2d-86d1-ed948588fbbb',
		now() - interval '2 days',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'7ad846a9-d55b-4035-8be2-dbcc70074f74',
		'recommendation',
		'4b7b3741-16ce-4ce8-a9b8-70556451a8e5',
		null,
		null,
		'tam',
		null,
		null,
		null
	),
	(
		'6cdc91b7-a7e6-4e7d-9769-868f16ae7361',
		now() - interval '2 days',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'7ad846a9-d55b-4035-8be2-dbcc70074f74',
		'request',
		null,
		null,
		null,
		'tam',
		'bc2e2811-1a9b-4131-981d-f2d7d7b26411',
		null,
		null
	),
	(
		'628f6f87-02d8-4f34-aeea-34b762bb6911',
		now() - interval '2 days',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'recommendation',
		'e24dd614-0033-4c9c-a72a-475f96dcfca6',
		null,
		null,
		'hin',
		null,
		null,
		null
	),
	(
		'ad6409d7-0853-43ba-925d-daaa754de1b4',
		now() - interval '47 hours',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'7ad846a9-d55b-4035-8be2-dbcc70074f74',
		'request',
		null,
		null,
		null,
		'hin',
		'e0d3a74e-4fe7-43c0-aa35-d05c83929986',
		null,
		null
	),
	(
		'208016d6-b27b-4c20-a4ed-ca6e9e9972e6',
		now() - interval '46 hours',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'request',
		null,
		null,
		null,
		'hin',
		'e0d3a74e-4fe7-43c0-aa35-d05c83929986',
		null,
		null
	);

--
-- friend_request_action (12 rows)
--
insert into
	"public"."friend_request_action" ("id", "uid_by", "uid_for", "created_at", "action_type", "uid_less", "uid_more")
values
	(
		'b4ff7858-00c6-4d8e-8dc5-0053b1e23ef7',
		'7ad846a9-d55b-4035-8be2-dbcc70074f74',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		now() - interval '60 days',
		'invite',
		'7ad846a9-d55b-4035-8be2-dbcc70074f74',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18'
	),
	(
		'37e51055-991e-4559-b237-930c5e969b31',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'7ad846a9-d55b-4035-8be2-dbcc70074f74',
		now() - interval '59 days',
		'accept',
		'7ad846a9-d55b-4035-8be2-dbcc70074f74',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18'
	),
	(
		'e9902b8c-54b6-4372-b6f6-fe25d499bd72',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'7ad846a9-d55b-4035-8be2-dbcc70074f74',
		now() - interval '58 days',
		'invite',
		'7ad846a9-d55b-4035-8be2-dbcc70074f74',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21'
	),
	(
		'c944af50-942e-4522-a000-b2cf19927026',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		now() - interval '57 days',
		'invite',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18'
	),
	(
		'7fcadd99-7f75-48eb-b288-320c9ec9d33e',
		'7ad846a9-d55b-4035-8be2-dbcc70074f74',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		now() - interval '56 days',
		'accept',
		'7ad846a9-d55b-4035-8be2-dbcc70074f74',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21'
	),
	(
		'104f367e-058c-4e50-bfd1-e35827dda31b',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		now() - interval '55 days',
		'accept',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18'
	),
	(
		'4a29d11e-29f9-475f-a539-071bcc79f7ff',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'a32f65e7-a496-4afc-abd3-798d8e6d9ec5',
		now() - interval '54 days',
		'invite',
		'a32f65e7-a496-4afc-abd3-798d8e6d9ec5',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18'
	),
	(
		'776e2fae-e83b-4fc8-88b9-a16ceb666045',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		now() - interval '53 days',
		'cancel',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18'
	),
	(
		'39b369c7-b6cb-4809-be89-60eb623ff5ba',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		now() - interval '52 days',
		'invite',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18'
	),
	(
		'23ff23c0-3d51-42bd-a4c9-28b9f00d607c',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		now() - interval '51 days',
		'accept',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18'
	),
	(
		'9335fd17-7943-4989-9058-e69671559bf1',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		now() - interval '50 days',
		'accept',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18'
	),
	(
		'4abd67bc-9b85-4ebd-b4ec-be7fc0e53e83',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		now() - interval '49 days',
		'accept',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18'
	);

--
-- user_profile (4 rows)
--
insert into
	"public"."user_profile" (
		"uid",
		"username",
		"updated_at",
		"created_at",
		"avatar_path",
		"languages_known",
		"font_preference",
		"review_answer_mode",
		"sound_enabled"
	)
values
	(
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'GarlicFace',
		null,
		now() - interval '30 days',
		'hyrax-197033.jpeg',
		'[{"lang":"eng","level":"fluent"},{"lang":"fra","level":"proficient"},{"lang":"fas","level":"proficient"}]',
		'default',
		'2-buttons',
		true
	),
	(
		'7ad846a9-d55b-4035-8be2-dbcc70074f74',
		'Lexigrine',
		null,
		now() - interval '3 days',
		'cartoon-face-288-1ac43e.png',
		'[{"lang":"eng","level":"fluent"}]',
		'default',
		'2-buttons',
		true
	),
	(
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'Best Frin',
		null,
		now() - interval '2 days',
		'red-bowl-1ad6ab.jpeg',
		'[{"lang":"eng","level":"fluent"},{"lang":"fra","level":"beginner"},{"lang":"hin","level":"beginner"}]',
		'default',
		'2-buttons',
		true
	),
	(
		'a32f65e7-a496-4afc-abd3-798d8e6d9ec5',
		'Work Andy',
		null,
		now() - interval '2 days',
		null,
		'[{"lang":"tam","level":"fluent"},{"lang":"hin","level":"fluent"},{"lang":"kan","level":"proficient"},{"lang":"eng","level":"fluent"},{"lang":"deu","level":"proficient"}]',
		'default',
		'2-buttons',
		true
	);

--
-- user_deck (12 rows)
--
insert into
	"public"."user_deck" (
		"id",
		"uid",
		"lang",
		"created_at",
		"learning_goal",
		"archived",
		"daily_review_goal",
		"preferred_translation_lang",
		"review_answer_mode",
		"updated_at"
	)
values
	(
		'dfa6cb07-5f8a-43d8-bc9f-5a9f474719c4',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'aka',
		now() - interval '30 days',
		'moving',
		true,
		15,
		null,
		null,
		now() - interval '2 hours'
	),
	(
		'e0b23bba-fe8c-4dfb-bdd6-65b2c60644f0',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tam',
		now() - interval '30 days',
		'moving',
		false,
		15,
		null,
		null,
		now() - interval '2 hours'
	),
	(
		'02be6d52-2f23-498d-ab24-a7cc0975c075',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'hin',
		now() - interval '30 days',
		'moving',
		false,
		15,
		null,
		null,
		now() - interval '2 hours'
	),
	(
		'8b73b2e9-8e32-4f9e-8044-67486e5e0399',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'mya',
		now() - interval '30 days',
		'moving',
		false,
		15,
		null,
		null,
		now() - interval '2 hours'
	),
	(
		'05000e6e-9b26-4632-b971-0df96a35c2bc',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'fra',
		now() - interval '30 days',
		'moving',
		false,
		15,
		null,
		null,
		now() - interval '2 hours'
	),
	(
		'7df47220-4003-43ad-99ba-0e9de75ace0b',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'ibo',
		now() - interval '30 days',
		'moving',
		false,
		15,
		null,
		null,
		now() - interval '2 hours'
	),
	(
		'c7053b11-4f34-4153-ad5a-9278d452949c',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'tam',
		now() - interval '30 days',
		'moving',
		false,
		15,
		null,
		null,
		now() - interval '2 hours'
	),
	(
		'e9259fbf-a94f-48f9-b8e6-5edfefc9c878',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'hin',
		now() - interval '30 days',
		'moving',
		false,
		15,
		null,
		null,
		now() - interval '2 hours'
	),
	(
		'9533bf48-fb98-4ace-befd-1eb1215e7f22',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'kan',
		now() - interval '15 days',
		'moving',
		false,
		15,
		null,
		null,
		now() - interval '2 hours'
	),
	(
		'3ea47a8a-3397-4658-9860-86cb607c43f2',
		'a2dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'kan',
		now() - interval '15 days',
		'moving',
		false,
		15,
		null,
		null,
		now() - interval '2 hours'
	),
	(
		'f8a7b3c1-2d4e-5f6a-8b9c-0d1e2f3a4b5c',
		'a32f65e7-a496-4afc-abd3-798d8e6d9ec5',
		'hin',
		now() - interval '30 days',
		'moving',
		false,
		15,
		null,
		null,
		now() - interval '2 hours'
	),
	(
		'b2c3d4e5-f6a7-4890-bcde-f1a2b3c4d5e6',
		'a32f65e7-a496-4afc-abd3-798d8e6d9ec5',
		'kan',
		now() - interval '15 days',
		'moving',
		false,
		15,
		null,
		null,
		now() - interval '2 hours'
	);
