set
	session_replication_role = replica;

-- generated by dump-new-seeds 2026-05-08T10:37:21.560Z
--
-- phrase (26 rows)
--
insert into
	"public"."phrase" ("text", "id", "added_by", "lang", "created_at", "text_script", "only_reverse", "archived")
values
	(
		'Aoo thodee Konkani ooloyta',
		'a417afc8-6c80-4589-a314-55ac756b28f1',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'kok',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Kitle',
		'd9da12a0-18f3-4836-af4b-8ea9423848ca',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'kok',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'kop khun [ka/krup]',
		'5b714f21-94e2-4345-88ca-7ea25a5bf988',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tha',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'gee baht [ka/krup]',
		'd546b14b-0bdf-48fa-9f55-0fa3ac1f3af7',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tha',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'kop khun [ka/krup]',
		'faae3442-2957-431d-b055-e8910b3c26ad',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'tha',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'grazi',
		'bca7ad96-44f4-4d58-b5b0-004f4450209a',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'ita',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'kai paije?',
		'99d430c1-5cbf-45aa-a95b-993e867ed668',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'mar',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'kai',
		'e9e0cdff-30b0-48fb-9816-285464943466',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'mar',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Tumhala kuthe zaichay?',
		'025301d1-00ef-45da-a1a0-d8382c4e5660',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'mar',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Hé kiti la aahë?',
		'3282e79e-3041-4adb-89fc-35d61f2f9eb8',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'mar',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Tumchyasathi mi kai karu?',
		'd155ec89-6bd2-411f-877f-51e96513dbc7',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'mar',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Aai chi gaand',
		'7d1461c8-a158-4633-b650-de7f83c7e436',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'mar',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Inshallah',
		'f250e23f-0aee-48d8-bb6f-1be22c0df7c7',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'ara',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Yalla',
		'0dd3a1d6-6a2c-4061-b6c0-51f6fb829082',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'ara',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Enjoy your meal',
		'95b1a0d4-666f-423d-a2b5-e7f27b5ea65c',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'I''m hungry',
		'674b81c7-eb26-4247-96cb-0c02378ee004',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'I promise',
		'b97d6fed-d12f-4272-b92c-7d8525550207',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'Shari',
		'a3532d81-0870-4e51-927c-59497d348fc9',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'mal',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'something',
		'7b915b5e-f8d2-4324-8d40-a2f00212875a',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'aar',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'something test',
		'1b33c04e-016e-4d12-a938-aa4ce8cd7596',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'aar',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'good luck',
		'7280cf0c-a394-40ee-92f4-0b68f08b16a2',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'good evening',
		'802bbec9-1c6c-49b8-8550-5efb71c39f54',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'It''s bad',
		'a29cea29-acbf-4ef9-bd00-8fab74c30335',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'I''m looking',
		'6eaf6b05-d83f-424b-9269-fd80611ecc4c',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'hello',
		'c545194f-b50f-4a44-bc75-a9f90a3538da',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		now() - interval '60 days',
		null,
		false,
		false
	),
	(
		'It''s raining',
		'6875a165-77bc-40d4-8430-699f71c3018a',
		'cf1f69ce-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		now() - interval '60 days',
		null,
		false,
		false
	);
