set
	session_replication_role = replica;

-- generated by dump-new-seeds 2026-05-08T08:38:15.528Z
--
-- request_comment (7 rows)
--
insert into
	"public"."request_comment" ("id", "request_id", "parent_comment_id", "uid", "content", "created_at", "updated_at", "upvote_count")
values
	(
		'f0000001-1111-4222-8333-444444444444',
		'f0d3a74e-4fe7-43c0-aa35-d05c83929986',
		null,
		'27ad846a-d55b-4035-8be2-dbcc70074f74',
		'Tu peux dire « Je voudrais un sandwich » — c''est la phrase classique',
		now() - interval '3 days',
		now() - interval '2 hours',
		5
	),
	(
		'f0000002-2222-4333-8444-555555555555',
		'f0d3a74e-4fe7-43c0-aa35-d05c83929986',
		'f0000001-1111-4222-8333-444444444444',
		'22dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'Merci beaucoup, c''est exactement ce qu''il me fallait!',
		now() - interval '3 days',
		now() - interval '2 hours',
		2
	),
	(
		'f0000003-3333-4444-8555-666666666666',
		'f40e53ce-0b24-4b5d-9cf4-5c1ac16d4f96',
		null,
		'22dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'Para sopa y café: "Una sopa y un café por favor" — ya lo añadí a mi colección',
		now() - interval '2 days',
		now() - interval '2 hours',
		3
	),
	(
		'f0000004-4444-4555-8666-777777777777',
		'f40e53ce-0b24-4b5d-9cf4-5c1ac16d4f96',
		null,
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'También puedes pedir un té',
		now() - interval '2 days',
		now() - interval '2 hours',
		1
	),
	(
		'f0000005-5555-4666-8777-888888888888',
		'f3f8c9e2-1234-4567-89ab-cdef01234567',
		null,
		'22dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'Belle question! Au marché tu peux montrer du doigt et dire « ça coûte combien? » ou « avez-vous des [item]? »',
		now() - interval '7 days',
		now() - interval '2 hours',
		4
	),
	(
		'f0000006-6666-7777-8888-999999999999',
		'f4a9d0f3-2345-5678-90bc-def012345678',
		null,
		'27ad846a-d55b-4035-8be2-dbcc70074f74',
		'En España la gente normalmente pregunta por "el aseo" en vez de "el baño"',
		now() - interval '6 days',
		now() - interval '2 hours',
		2
	),
	(
		'f00d41d1-3161-4a22-9d6f-dd0dcb29374a',
		'f40e53ce-0b24-4b5d-9cf4-5c1ac16d4f96',
		null,
		'22dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'Solo di "dame uno" así',
		now() - interval '25 hours',
		now() - interval '2 hours',
		5
	);

--
-- playlist_phrase_link (4 rows)
--
insert into
	"public"."playlist_phrase_link" ("id", "uid", "phrase_id", "playlist_id", "order", "href", "created_at")
values
	(
		'f1111111-aaaa-4bbb-8ccc-dddddddddddd',
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'fa110001-1111-4aaa-bbbb-cccccccccccc',
		'f1b2c3d4-1111-4222-a333-444444444444',
		1,
		null,
		now() - interval '15 days'
	),
	(
		'f2222222-bbbb-4ccc-8ddd-eeeeeeeeeeee',
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'fa110004-4444-4aaa-bbbb-cccccccccccc',
		'f1b2c3d4-1111-4222-a333-444444444444',
		2,
		null,
		now() - interval '15 days'
	),
	(
		'f3333333-cccc-4ddd-8eee-ffffffffffff',
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'f9e3edac-de8b-4796-b436-a0cded08d2ae',
		'f3d4e5f6-3333-4444-a555-666666666666',
		1,
		null,
		now() - interval '10 days'
	),
	(
		'f4444444-dddd-4eee-8fff-000000000000',
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'f0fbbe1d-705e-4d93-a231-ac55263fcfee',
		'f3d4e5f6-3333-4444-a555-666666666666',
		2,
		null,
		now() - interval '10 days'
	);

--
-- comment_phrase_link (2 rows)
--
insert into
	"public"."comment_phrase_link" ("id", "request_id", "comment_id", "phrase_id", "uid", "created_at")
values
	(
		'faaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',
		'f0d3a74e-4fe7-43c0-aa35-d05c83929986',
		'f0000001-1111-4222-8333-444444444444',
		'fa110009-9999-4aaa-bbbb-cccccccccccc',
		'27ad846a-d55b-4035-8be2-dbcc70074f74',
		now() - interval '3 days'
	),
	(
		'fd14296c-da0c-4463-a547-fa6538d1341a',
		'f40e53ce-0b24-4b5d-9cf4-5c1ac16d4f96',
		'f00d41d1-3161-4a22-9d6f-dd0dcb29374a',
		'f0fbbe1d-705e-4d93-a231-ac55263fcfee',
		'22dfa256-ef7b-41b0-b05a-d97afab8dd21',
		now() - interval '25 hours'
	);

--
-- phrase_translation (18 rows)
--
insert into
	"public"."phrase_translation" ("text", "literal", "id", "phrase_id", "added_by", "lang", "text_script", "created_at", "archived", "updated_at")
values
	(
		'Hello',
		null,
		'fa221001-1111-4aaa-bbbb-cccccccccccc',
		'fa110001-1111-4aaa-bbbb-cccccccccccc',
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		null,
		now() - interval '25 days',
		false,
		now() - interval '2 hours'
	),
	(
		'Good evening',
		null,
		'fa221002-2222-4aaa-bbbb-cccccccccccc',
		'fa110002-2222-4aaa-bbbb-cccccccccccc',
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		null,
		now() - interval '24 days',
		false,
		now() - interval '2 hours'
	),
	(
		'How are you?',
		null,
		'fa221003-3333-4aaa-bbbb-cccccccccccc',
		'fa110003-3333-4aaa-bbbb-cccccccccccc',
		'22dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'eng',
		null,
		now() - interval '23 days',
		false,
		now() - interval '2 hours'
	),
	(
		'Thank you very much',
		null,
		'fa221004-4444-4aaa-bbbb-cccccccccccc',
		'fa110004-4444-4aaa-bbbb-cccccccccccc',
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		null,
		now() - interval '22 days',
		false,
		now() - interval '2 hours'
	),
	(
		'Please',
		null,
		'fa221005-5555-4aaa-bbbb-cccccccccccc',
		'fa110005-5555-4aaa-bbbb-cccccccccccc',
		'22dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'eng',
		null,
		now() - interval '21 days',
		false,
		now() - interval '2 hours'
	),
	(
		'Goodbye',
		null,
		'fa221008-8888-4aaa-bbbb-cccccccccccc',
		'fa110008-8888-4aaa-bbbb-cccccccccccc',
		'22dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'eng',
		null,
		now() - interval '20 days',
		false,
		now() - interval '2 hours'
	),
	(
		'Excuse me',
		null,
		'fa221009-9999-4aaa-bbbb-cccccccccccc',
		'fa110009-9999-4aaa-bbbb-cccccccccccc',
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		null,
		now() - interval '19 days',
		false,
		now() - interval '2 hours'
	),
	(
		'I do not understand',
		null,
		'fa221010-0000-4aaa-bbbb-cccccccccccc',
		'fa110010-0000-4aaa-bbbb-cccccccccccc',
		'27ad846a-d55b-4035-8be2-dbcc70074f74',
		'eng',
		null,
		now() - interval '18 days',
		false,
		now() - interval '2 hours'
	),
	(
		'Where are the toilets?',
		null,
		'fa221011-1111-4bbb-bbbb-cccccccccccc',
		'fa110011-1111-4bbb-bbbb-cccccccccccc',
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		null,
		now() - interval '17 days',
		false,
		now() - interval '2 hours'
	),
	(
		'I would like a coffee',
		null,
		'fa221012-2222-4bbb-bbbb-cccccccccccc',
		'fa110012-2222-4bbb-bbbb-cccccccccccc',
		'22dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'eng',
		null,
		now() - interval '16 days',
		false,
		now() - interval '2 hours'
	),
	(
		'See you tomorrow',
		null,
		'fa221013-3333-4bbb-bbbb-cccccccccccc',
		'fa110013-3333-4bbb-bbbb-cccccccccccc',
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		null,
		now() - interval '15 days',
		false,
		now() - interval '2 hours'
	),
	(
		'Good night',
		null,
		'fa221014-4444-4bbb-bbbb-cccccccccccc',
		'fa110014-4444-4bbb-bbbb-cccccccccccc',
		'22dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'eng',
		null,
		now() - interval '14 days',
		false,
		now() - interval '2 hours'
	),
	(
		'Hello everyone',
		null,
		'fa222001-1111-4aaa-bbbb-cccccccccccc',
		'f2bae84f-5b1d-43c2-8927-ef4d41c7e794',
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		null,
		now() - interval '13 days',
		false,
		now() - interval '2 hours'
	),
	(
		'Hello friend',
		null,
		'fb221006-6666-4aaa-bbbb-cccccccccccc',
		'ff110006-6666-4aaa-bbbb-cccccccccccc',
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		null,
		now() - interval '20 days',
		false,
		now() - interval '2 hours'
	),
	(
		'Happy new year',
		null,
		'fb221007-7777-4aaa-bbbb-cccccccccccc',
		'ff110007-7777-4aaa-bbbb-cccccccccccc',
		'2a32f65e-a496-4afc-abd3-798d8e6d9ec5',
		'eng',
		null,
		now() - interval '18 days',
		false,
		now() - interval '2 hours'
	),
	(
		'Soup and a coffee please',
		null,
		'fb22fbe1-705e-4d93-a231-ac55263fcfee',
		'f0fbbe1d-705e-4d93-a231-ac55263fcfee',
		'22dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'eng',
		null,
		now() - interval '15 days',
		false,
		now() - interval '2 hours'
	),
	(
		'Good morning',
		null,
		'fb22e3da-de8b-4796-b436-a0cded08d2ae',
		'f9e3edac-de8b-4796-b436-a0cded08d2ae',
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'eng',
		null,
		now() - interval '12 days',
		false,
		now() - interval '2 hours'
	),
	(
		'Thank you',
		null,
		'fb221008-8888-4aaa-bbbb-cccccccccccc',
		'fb110008-8888-4aaa-bbbb-cccccccccccc',
		'22dfa256-ef7b-41b0-b05a-d97afab8dd21',
		'eng',
		null,
		now() - interval '10 days',
		false,
		now() - interval '2 hours'
	);

--
-- user_card (14 rows)
--
insert into
	"public"."user_card" ("uid", "id", "phrase_id", "updated_at", "created_at", "status", "lang", "direction")
values
	(
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'fc110001-1111-4aaa-bbbb-222222222222',
		'fa110001-1111-4aaa-bbbb-cccccccccccc',
		now() - interval '20 days',
		now() - interval '20 days',
		'active',
		'fra',
		'forward'
	),
	(
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'fc110002-2222-4aaa-bbbb-222222222222',
		'fa110002-2222-4aaa-bbbb-cccccccccccc',
		now() - interval '20 days',
		now() - interval '20 days',
		'active',
		'fra',
		'forward'
	),
	(
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'fc110003-3333-4aaa-bbbb-222222222222',
		'fa110003-3333-4aaa-bbbb-cccccccccccc',
		now() - interval '20 days',
		now() - interval '20 days',
		'active',
		'fra',
		'forward'
	),
	(
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'fc110004-4444-4aaa-bbbb-222222222222',
		'fa110004-4444-4aaa-bbbb-cccccccccccc',
		now() - interval '20 days',
		now() - interval '20 days',
		'active',
		'fra',
		'forward'
	),
	(
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'fc110005-5555-4aaa-bbbb-222222222222',
		'fa110005-5555-4aaa-bbbb-cccccccccccc',
		now() - interval '20 days',
		now() - interval '20 days',
		'active',
		'fra',
		'forward'
	),
	(
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'fc110008-8888-4aaa-bbbb-222222222222',
		'fa110008-8888-4aaa-bbbb-cccccccccccc',
		now() - interval '20 days',
		now() - interval '20 days',
		'active',
		'fra',
		'forward'
	),
	(
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'fc110009-9999-4aaa-bbbb-222222222222',
		'fa110009-9999-4aaa-bbbb-cccccccccccc',
		now() - interval '20 days',
		now() - interval '20 days',
		'active',
		'fra',
		'forward'
	),
	(
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'fc110010-0000-4aaa-bbbb-222222222222',
		'fa110010-0000-4aaa-bbbb-cccccccccccc',
		now() - interval '20 days',
		now() - interval '20 days',
		'active',
		'fra',
		'forward'
	),
	(
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'fc110011-1111-4bbb-bbbb-222222222222',
		'fa110011-1111-4bbb-bbbb-cccccccccccc',
		now() - interval '20 days',
		now() - interval '20 days',
		'active',
		'fra',
		'forward'
	),
	(
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'fc110012-2222-4bbb-bbbb-222222222222',
		'fa110012-2222-4bbb-bbbb-cccccccccccc',
		now() - interval '20 days',
		now() - interval '20 days',
		'active',
		'fra',
		'forward'
	),
	(
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'fc110013-3333-4bbb-bbbb-222222222222',
		'fa110013-3333-4bbb-bbbb-cccccccccccc',
		now() - interval '20 days',
		now() - interval '20 days',
		'active',
		'fra',
		'forward'
	),
	(
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'fc110014-4444-4bbb-bbbb-222222222222',
		'fa110014-4444-4bbb-bbbb-cccccccccccc',
		now() - interval '20 days',
		now() - interval '20 days',
		'active',
		'fra',
		'forward'
	),
	(
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'fc110015-1111-4ccc-bbbb-222222222222',
		'f2bae84f-5b1d-43c2-8927-ef4d41c7e794',
		now() - interval '20 days',
		now() - interval '20 days',
		'active',
		'fra',
		'forward'
	),
	(
		'21f1f69c-10fa-4059-8fd4-3c6dcef9ba18',
		'fc220006-6666-4aaa-bbbb-222222222222',
		'ff110006-6666-4aaa-bbbb-cccccccccccc',
		now() - interval '12 days',
		now() - interval '12 days',
		'active',
		'spa',
		'forward'
	);
