name: 'electricsql_service'

services:
  electric:
    image: docker.io/electricsql/electric:latest
    environment:
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:54322/postgres?sslmode=disable
      # Not suitable for production. Only use insecure mode in development or if you've otherwise secured the Electric API.
      # See https://electric-sql.com/docs/guides/security
      ELECTRIC_INSECURE: true
    ports:
      - '3000:3000'
    #depends_on:
    #  postgres:
    #    condition: service_healthy
