/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/_user'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserWelcomeRouteImport } from './routes/_user/welcome'
import { Route as UserSearchRouteImport } from './routes/_user/search'
import { Route as UserProfileRouteImport } from './routes/_user/profile'
import { Route as UserNotificationsRouteImport } from './routes/_user/notifications'
import { Route as UserLearnRouteImport } from './routes/_user/learn'
import { Route as UserGettingStartedRouteImport } from './routes/_user/getting-started'
import { Route as UserFriendsRouteImport } from './routes/_user/friends'
import { Route as UserAdminRouteImport } from './routes/_user/admin'
import { Route as UserAcceptInviteRouteImport } from './routes/_user/accept-invite'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSetNewPasswordRouteImport } from './routes/_auth/set-new-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as UserProfileIndexRouteImport } from './routes/_user/profile/index'
import { Route as UserLearnIndexRouteImport } from './routes/_user/learn/index'
import { Route as UserFriendsIndexRouteImport } from './routes/_user/friends/index'
import { Route as UserAdminIndexRouteImport } from './routes/_user/admin/index'
import { Route as UserProfileChangePasswordRouteImport } from './routes/_user/profile/change-password'
import { Route as UserProfileChangeEmailConfirmRouteImport } from './routes/_user/profile/change-email-confirm'
import { Route as UserProfileChangeEmailRouteImport } from './routes/_user/profile/change-email'
import { Route as UserLearnContributionsRouteImport } from './routes/_user/learn/contributions'
import { Route as UserLearnBrowseRouteImport } from './routes/_user/learn/browse'
import { Route as UserLearnArchivedRouteImport } from './routes/_user/learn/archived'
import { Route as UserLearnAddDeckRouteImport } from './routes/_user/learn/add-deck'
import { Route as UserLearnLangRouteImport } from './routes/_user/learn/$lang'
import { Route as UserFriendsChatsRouteImport } from './routes/_user/friends/chats'
import { Route as UserFriendsUidRouteImport } from './routes/_user/friends/$uid'
import { Route as UserAdminLangRouteImport } from './routes/_user/admin/$lang'
import { Route as UserLearnBrowseIndexRouteImport } from './routes/_user/learn/browse.index'
import { Route as UserLearnLangIndexRouteImport } from './routes/_user/learn/$lang.index'
import { Route as UserFriendsChatsIndexRouteImport } from './routes/_user/friends/chats.index'
import { Route as UserAdminLangIndexRouteImport } from './routes/_user/admin/$lang.index'
import { Route as UserLearnBrowseChartsRouteImport } from './routes/_user/learn/browse.charts'
import { Route as UserLearnLangStatsRouteImport } from './routes/_user/learn/$lang.stats'
import { Route as UserLearnLangReviewRouteImport } from './routes/_user/learn/$lang.review'
import { Route as UserLearnLangPlaylistsRouteImport } from './routes/_user/learn/$lang.playlists'
import { Route as UserLearnLangManageDeckRouteImport } from './routes/_user/learn/$lang.manage-deck'
import { Route as UserLearnLangFeedRouteImport } from './routes/_user/learn/$lang.feed'
import { Route as UserLearnLangDeckSettingsRouteImport } from './routes/_user/learn/$lang.deck-settings'
import { Route as UserLearnLangContributionsRouteImport } from './routes/_user/learn/$lang.contributions'
import { Route as UserLearnLangBulkAddRouteImport } from './routes/_user/learn/$lang.bulk-add'
import { Route as UserFriendsChatsFriendUidRouteImport } from './routes/_user/friends/chats.$friendUid'
import { Route as UserAdminLangRequestsRouteImport } from './routes/_user/admin/$lang.requests'
import { Route as UserAdminLangPhrasesRouteImport } from './routes/_user/admin/$lang.phrases'
import { Route as UserLearnLangReviewIndexRouteImport } from './routes/_user/learn/$lang.review.index'
import { Route as UserLearnLangRequestsIndexRouteImport } from './routes/_user/learn/$lang.requests.index'
import { Route as UserLearnLangPlaylistsIndexRouteImport } from './routes/_user/learn/$lang.playlists.index'
import { Route as UserAdminLangRequestsIndexRouteImport } from './routes/_user/admin/$lang.requests.index'
import { Route as UserAdminLangPhrasesIndexRouteImport } from './routes/_user/admin/$lang.phrases.index'
import { Route as UserLearnLangReviewPreviewRouteImport } from './routes/_user/learn/$lang.review.preview'
import { Route as UserLearnLangReviewGoRouteImport } from './routes/_user/learn/$lang.review.go'
import { Route as UserLearnLangRequestsNewRouteImport } from './routes/_user/learn/$lang.requests.new'
import { Route as UserLearnLangRequestsIdRouteImport } from './routes/_user/learn/$lang.requests.$id'
import { Route as UserLearnLangPlaylistsNewRouteImport } from './routes/_user/learn/$lang.playlists.new'
import { Route as UserLearnLangPlaylistsPlaylistIdRouteImport } from './routes/_user/learn/$lang.playlists.$playlistId'
import { Route as UserLearnLangPhrasesNewRouteImport } from './routes/_user/learn/$lang.phrases.new'
import { Route as UserLearnLangPhrasesIdRouteImport } from './routes/_user/learn/$lang.phrases.$id'
import { Route as UserFriendsChatsFriendUidRecommendRouteImport } from './routes/_user/friends/chats.$friendUid.recommend'
import { Route as UserAdminLangRequestsIdRouteImport } from './routes/_user/admin/$lang.requests.$id'
import { Route as UserAdminLangPhrasesIdRouteImport } from './routes/_user/admin/$lang.phrases.$id'

const ThemesLazyRouteImport = createFileRoute('/themes')()
const RequestRemovalLazyRouteImport = createFileRoute('/request-removal')()
const PrivacyPolicyLazyRouteImport = createFileRoute('/privacy-policy')()
const MicrocopyLazyRouteImport = createFileRoute('/microcopy')()
const ComponentsLazyRouteImport = createFileRoute('/components')()
const UserFriendsInviteLazyRouteImport = createFileRoute(
  '/_user/friends/invite',
)()

const ThemesLazyRoute = ThemesLazyRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/themes.lazy').then((d) => d.Route))
const RequestRemovalLazyRoute = RequestRemovalLazyRouteImport.update({
  id: '/request-removal',
  path: '/request-removal',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/request-removal.lazy').then((d) => d.Route),
)
const PrivacyPolicyLazyRoute = PrivacyPolicyLazyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/privacy-policy.lazy').then((d) => d.Route),
)
const MicrocopyLazyRoute = MicrocopyLazyRouteImport.update({
  id: '/microcopy',
  path: '/microcopy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/microcopy.lazy').then((d) => d.Route))
const ComponentsLazyRoute = ComponentsLazyRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/components.lazy').then((d) => d.Route))
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserWelcomeRoute = UserWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => UserRoute,
} as any)
const UserSearchRoute = UserSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserNotificationsRoute = UserNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => UserRoute,
} as any)
const UserLearnRoute = UserLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => UserRoute,
} as any)
const UserGettingStartedRoute = UserGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => UserRoute,
} as any)
const UserFriendsRoute = UserFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => UserRoute,
} as any)
const UserAdminRoute = UserAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => UserRoute,
} as any)
const UserAcceptInviteRoute = UserAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => UserRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSetNewPasswordRoute = AuthSetNewPasswordRouteImport.update({
  id: '/set-new-password',
  path: '/set-new-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const UserProfileIndexRoute = UserProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserProfileRoute,
} as any)
const UserLearnIndexRoute = UserLearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserLearnRoute,
} as any)
const UserFriendsIndexRoute = UserFriendsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserFriendsRoute,
} as any)
const UserAdminIndexRoute = UserAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserAdminRoute,
} as any)
const UserFriendsInviteLazyRoute = UserFriendsInviteLazyRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => UserFriendsRoute,
} as any).lazy(() =>
  import('./routes/_user/friends/invite.lazy').then((d) => d.Route),
)
const UserProfileChangePasswordRoute =
  UserProfileChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => UserProfileRoute,
  } as any)
const UserProfileChangeEmailConfirmRoute =
  UserProfileChangeEmailConfirmRouteImport.update({
    id: '/change-email-confirm',
    path: '/change-email-confirm',
    getParentRoute: () => UserProfileRoute,
  } as any)
const UserProfileChangeEmailRoute = UserProfileChangeEmailRouteImport.update({
  id: '/change-email',
  path: '/change-email',
  getParentRoute: () => UserProfileRoute,
} as any)
const UserLearnContributionsRoute = UserLearnContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => UserLearnRoute,
} as any)
const UserLearnBrowseRoute = UserLearnBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => UserLearnRoute,
} as any)
const UserLearnArchivedRoute = UserLearnArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => UserLearnRoute,
} as any)
const UserLearnAddDeckRoute = UserLearnAddDeckRouteImport.update({
  id: '/add-deck',
  path: '/add-deck',
  getParentRoute: () => UserLearnRoute,
} as any)
const UserLearnLangRoute = UserLearnLangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => UserLearnRoute,
} as any)
const UserFriendsChatsRoute = UserFriendsChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => UserFriendsRoute,
} as any)
const UserFriendsUidRoute = UserFriendsUidRouteImport.update({
  id: '/$uid',
  path: '/$uid',
  getParentRoute: () => UserFriendsRoute,
} as any)
const UserAdminLangRoute = UserAdminLangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => UserAdminRoute,
} as any)
const UserLearnBrowseIndexRoute = UserLearnBrowseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserLearnBrowseRoute,
} as any)
const UserLearnLangIndexRoute = UserLearnLangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserLearnLangRoute,
} as any)
const UserFriendsChatsIndexRoute = UserFriendsChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserFriendsChatsRoute,
} as any)
const UserAdminLangIndexRoute = UserAdminLangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserAdminLangRoute,
} as any)
const UserLearnBrowseChartsRoute = UserLearnBrowseChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => UserLearnBrowseRoute,
} as any)
const UserLearnLangStatsRoute = UserLearnLangStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => UserLearnLangRoute,
} as any)
const UserLearnLangReviewRoute = UserLearnLangReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => UserLearnLangRoute,
} as any)
const UserLearnLangPlaylistsRoute = UserLearnLangPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => UserLearnLangRoute,
} as any)
const UserLearnLangManageDeckRoute = UserLearnLangManageDeckRouteImport.update({
  id: '/manage-deck',
  path: '/manage-deck',
  getParentRoute: () => UserLearnLangRoute,
} as any)
const UserLearnLangFeedRoute = UserLearnLangFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => UserLearnLangRoute,
} as any)
const UserLearnLangDeckSettingsRoute =
  UserLearnLangDeckSettingsRouteImport.update({
    id: '/deck-settings',
    path: '/deck-settings',
    getParentRoute: () => UserLearnLangRoute,
  } as any)
const UserLearnLangContributionsRoute =
  UserLearnLangContributionsRouteImport.update({
    id: '/contributions',
    path: '/contributions',
    getParentRoute: () => UserLearnLangRoute,
  } as any)
const UserLearnLangBulkAddRoute = UserLearnLangBulkAddRouteImport.update({
  id: '/bulk-add',
  path: '/bulk-add',
  getParentRoute: () => UserLearnLangRoute,
} as any)
const UserFriendsChatsFriendUidRoute =
  UserFriendsChatsFriendUidRouteImport.update({
    id: '/$friendUid',
    path: '/$friendUid',
    getParentRoute: () => UserFriendsChatsRoute,
  } as any)
const UserAdminLangRequestsRoute = UserAdminLangRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => UserAdminLangRoute,
} as any)
const UserAdminLangPhrasesRoute = UserAdminLangPhrasesRouteImport.update({
  id: '/phrases',
  path: '/phrases',
  getParentRoute: () => UserAdminLangRoute,
} as any)
const UserLearnLangReviewIndexRoute =
  UserLearnLangReviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserLearnLangReviewRoute,
  } as any)
const UserLearnLangRequestsIndexRoute =
  UserLearnLangRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => UserLearnLangRoute,
  } as any)
const UserLearnLangPlaylistsIndexRoute =
  UserLearnLangPlaylistsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserLearnLangPlaylistsRoute,
  } as any)
const UserAdminLangRequestsIndexRoute =
  UserAdminLangRequestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserAdminLangRequestsRoute,
  } as any)
const UserAdminLangPhrasesIndexRoute =
  UserAdminLangPhrasesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserAdminLangPhrasesRoute,
  } as any)
const UserLearnLangReviewPreviewRoute =
  UserLearnLangReviewPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => UserLearnLangReviewRoute,
  } as any)
const UserLearnLangReviewGoRoute = UserLearnLangReviewGoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => UserLearnLangReviewRoute,
} as any)
const UserLearnLangRequestsNewRoute =
  UserLearnLangRequestsNewRouteImport.update({
    id: '/requests/new',
    path: '/requests/new',
    getParentRoute: () => UserLearnLangRoute,
  } as any)
const UserLearnLangRequestsIdRoute = UserLearnLangRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => UserLearnLangRoute,
} as any)
const UserLearnLangPlaylistsNewRoute =
  UserLearnLangPlaylistsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => UserLearnLangPlaylistsRoute,
  } as any)
const UserLearnLangPlaylistsPlaylistIdRoute =
  UserLearnLangPlaylistsPlaylistIdRouteImport.update({
    id: '/$playlistId',
    path: '/$playlistId',
    getParentRoute: () => UserLearnLangPlaylistsRoute,
  } as any)
const UserLearnLangPhrasesNewRoute = UserLearnLangPhrasesNewRouteImport.update({
  id: '/phrases/new',
  path: '/phrases/new',
  getParentRoute: () => UserLearnLangRoute,
} as any)
const UserLearnLangPhrasesIdRoute = UserLearnLangPhrasesIdRouteImport.update({
  id: '/phrases/$id',
  path: '/phrases/$id',
  getParentRoute: () => UserLearnLangRoute,
} as any)
const UserFriendsChatsFriendUidRecommendRoute =
  UserFriendsChatsFriendUidRecommendRouteImport.update({
    id: '/recommend',
    path: '/recommend',
    getParentRoute: () => UserFriendsChatsFriendUidRoute,
  } as any)
const UserAdminLangRequestsIdRoute = UserAdminLangRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UserAdminLangRequestsRoute,
} as any)
const UserAdminLangPhrasesIdRoute = UserAdminLangPhrasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UserAdminLangPhrasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsLazyRoute
  '/microcopy': typeof MicrocopyLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/request-removal': typeof RequestRemovalLazyRoute
  '/themes': typeof ThemesLazyRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/set-new-password': typeof AuthSetNewPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/accept-invite': typeof UserAcceptInviteRoute
  '/admin': typeof UserAdminRouteWithChildren
  '/friends': typeof UserFriendsRouteWithChildren
  '/getting-started': typeof UserGettingStartedRoute
  '/learn': typeof UserLearnRouteWithChildren
  '/notifications': typeof UserNotificationsRoute
  '/profile': typeof UserProfileRouteWithChildren
  '/search': typeof UserSearchRoute
  '/welcome': typeof UserWelcomeRoute
  '/admin/$lang': typeof UserAdminLangRouteWithChildren
  '/friends/$uid': typeof UserFriendsUidRoute
  '/friends/chats': typeof UserFriendsChatsRouteWithChildren
  '/learn/$lang': typeof UserLearnLangRouteWithChildren
  '/learn/add-deck': typeof UserLearnAddDeckRoute
  '/learn/archived': typeof UserLearnArchivedRoute
  '/learn/browse': typeof UserLearnBrowseRouteWithChildren
  '/learn/contributions': typeof UserLearnContributionsRoute
  '/profile/change-email': typeof UserProfileChangeEmailRoute
  '/profile/change-email-confirm': typeof UserProfileChangeEmailConfirmRoute
  '/profile/change-password': typeof UserProfileChangePasswordRoute
  '/friends/invite': typeof UserFriendsInviteLazyRoute
  '/admin/': typeof UserAdminIndexRoute
  '/friends/': typeof UserFriendsIndexRoute
  '/learn/': typeof UserLearnIndexRoute
  '/profile/': typeof UserProfileIndexRoute
  '/admin/$lang/phrases': typeof UserAdminLangPhrasesRouteWithChildren
  '/admin/$lang/requests': typeof UserAdminLangRequestsRouteWithChildren
  '/friends/chats/$friendUid': typeof UserFriendsChatsFriendUidRouteWithChildren
  '/learn/$lang/bulk-add': typeof UserLearnLangBulkAddRoute
  '/learn/$lang/contributions': typeof UserLearnLangContributionsRoute
  '/learn/$lang/deck-settings': typeof UserLearnLangDeckSettingsRoute
  '/learn/$lang/feed': typeof UserLearnLangFeedRoute
  '/learn/$lang/manage-deck': typeof UserLearnLangManageDeckRoute
  '/learn/$lang/playlists': typeof UserLearnLangPlaylistsRouteWithChildren
  '/learn/$lang/review': typeof UserLearnLangReviewRouteWithChildren
  '/learn/$lang/stats': typeof UserLearnLangStatsRoute
  '/learn/browse/charts': typeof UserLearnBrowseChartsRoute
  '/admin/$lang/': typeof UserAdminLangIndexRoute
  '/friends/chats/': typeof UserFriendsChatsIndexRoute
  '/learn/$lang/': typeof UserLearnLangIndexRoute
  '/learn/browse/': typeof UserLearnBrowseIndexRoute
  '/admin/$lang/phrases/$id': typeof UserAdminLangPhrasesIdRoute
  '/admin/$lang/requests/$id': typeof UserAdminLangRequestsIdRoute
  '/friends/chats/$friendUid/recommend': typeof UserFriendsChatsFriendUidRecommendRoute
  '/learn/$lang/phrases/$id': typeof UserLearnLangPhrasesIdRoute
  '/learn/$lang/phrases/new': typeof UserLearnLangPhrasesNewRoute
  '/learn/$lang/playlists/$playlistId': typeof UserLearnLangPlaylistsPlaylistIdRoute
  '/learn/$lang/playlists/new': typeof UserLearnLangPlaylistsNewRoute
  '/learn/$lang/requests/$id': typeof UserLearnLangRequestsIdRoute
  '/learn/$lang/requests/new': typeof UserLearnLangRequestsNewRoute
  '/learn/$lang/review/go': typeof UserLearnLangReviewGoRoute
  '/learn/$lang/review/preview': typeof UserLearnLangReviewPreviewRoute
  '/admin/$lang/phrases/': typeof UserAdminLangPhrasesIndexRoute
  '/admin/$lang/requests/': typeof UserAdminLangRequestsIndexRoute
  '/learn/$lang/playlists/': typeof UserLearnLangPlaylistsIndexRoute
  '/learn/$lang/requests/': typeof UserLearnLangRequestsIndexRoute
  '/learn/$lang/review/': typeof UserLearnLangReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsLazyRoute
  '/microcopy': typeof MicrocopyLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/request-removal': typeof RequestRemovalLazyRoute
  '/themes': typeof ThemesLazyRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/set-new-password': typeof AuthSetNewPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/accept-invite': typeof UserAcceptInviteRoute
  '/getting-started': typeof UserGettingStartedRoute
  '/notifications': typeof UserNotificationsRoute
  '/search': typeof UserSearchRoute
  '/welcome': typeof UserWelcomeRoute
  '/friends/$uid': typeof UserFriendsUidRoute
  '/learn/add-deck': typeof UserLearnAddDeckRoute
  '/learn/archived': typeof UserLearnArchivedRoute
  '/learn/contributions': typeof UserLearnContributionsRoute
  '/profile/change-email': typeof UserProfileChangeEmailRoute
  '/profile/change-email-confirm': typeof UserProfileChangeEmailConfirmRoute
  '/profile/change-password': typeof UserProfileChangePasswordRoute
  '/friends/invite': typeof UserFriendsInviteLazyRoute
  '/admin': typeof UserAdminIndexRoute
  '/friends': typeof UserFriendsIndexRoute
  '/learn': typeof UserLearnIndexRoute
  '/profile': typeof UserProfileIndexRoute
  '/friends/chats/$friendUid': typeof UserFriendsChatsFriendUidRouteWithChildren
  '/learn/$lang/bulk-add': typeof UserLearnLangBulkAddRoute
  '/learn/$lang/contributions': typeof UserLearnLangContributionsRoute
  '/learn/$lang/deck-settings': typeof UserLearnLangDeckSettingsRoute
  '/learn/$lang/feed': typeof UserLearnLangFeedRoute
  '/learn/$lang/manage-deck': typeof UserLearnLangManageDeckRoute
  '/learn/$lang/stats': typeof UserLearnLangStatsRoute
  '/learn/browse/charts': typeof UserLearnBrowseChartsRoute
  '/admin/$lang': typeof UserAdminLangIndexRoute
  '/friends/chats': typeof UserFriendsChatsIndexRoute
  '/learn/$lang': typeof UserLearnLangIndexRoute
  '/learn/browse': typeof UserLearnBrowseIndexRoute
  '/admin/$lang/phrases/$id': typeof UserAdminLangPhrasesIdRoute
  '/admin/$lang/requests/$id': typeof UserAdminLangRequestsIdRoute
  '/friends/chats/$friendUid/recommend': typeof UserFriendsChatsFriendUidRecommendRoute
  '/learn/$lang/phrases/$id': typeof UserLearnLangPhrasesIdRoute
  '/learn/$lang/phrases/new': typeof UserLearnLangPhrasesNewRoute
  '/learn/$lang/playlists/$playlistId': typeof UserLearnLangPlaylistsPlaylistIdRoute
  '/learn/$lang/playlists/new': typeof UserLearnLangPlaylistsNewRoute
  '/learn/$lang/requests/$id': typeof UserLearnLangRequestsIdRoute
  '/learn/$lang/requests/new': typeof UserLearnLangRequestsNewRoute
  '/learn/$lang/review/go': typeof UserLearnLangReviewGoRoute
  '/learn/$lang/review/preview': typeof UserLearnLangReviewPreviewRoute
  '/admin/$lang/phrases': typeof UserAdminLangPhrasesIndexRoute
  '/admin/$lang/requests': typeof UserAdminLangRequestsIndexRoute
  '/learn/$lang/playlists': typeof UserLearnLangPlaylistsIndexRoute
  '/learn/$lang/requests': typeof UserLearnLangRequestsIndexRoute
  '/learn/$lang/review': typeof UserLearnLangReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_user': typeof UserRouteWithChildren
  '/components': typeof ComponentsLazyRoute
  '/microcopy': typeof MicrocopyLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/request-removal': typeof RequestRemovalLazyRoute
  '/themes': typeof ThemesLazyRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/set-new-password': typeof AuthSetNewPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_user/accept-invite': typeof UserAcceptInviteRoute
  '/_user/admin': typeof UserAdminRouteWithChildren
  '/_user/friends': typeof UserFriendsRouteWithChildren
  '/_user/getting-started': typeof UserGettingStartedRoute
  '/_user/learn': typeof UserLearnRouteWithChildren
  '/_user/notifications': typeof UserNotificationsRoute
  '/_user/profile': typeof UserProfileRouteWithChildren
  '/_user/search': typeof UserSearchRoute
  '/_user/welcome': typeof UserWelcomeRoute
  '/_user/admin/$lang': typeof UserAdminLangRouteWithChildren
  '/_user/friends/$uid': typeof UserFriendsUidRoute
  '/_user/friends/chats': typeof UserFriendsChatsRouteWithChildren
  '/_user/learn/$lang': typeof UserLearnLangRouteWithChildren
  '/_user/learn/add-deck': typeof UserLearnAddDeckRoute
  '/_user/learn/archived': typeof UserLearnArchivedRoute
  '/_user/learn/browse': typeof UserLearnBrowseRouteWithChildren
  '/_user/learn/contributions': typeof UserLearnContributionsRoute
  '/_user/profile/change-email': typeof UserProfileChangeEmailRoute
  '/_user/profile/change-email-confirm': typeof UserProfileChangeEmailConfirmRoute
  '/_user/profile/change-password': typeof UserProfileChangePasswordRoute
  '/_user/friends/invite': typeof UserFriendsInviteLazyRoute
  '/_user/admin/': typeof UserAdminIndexRoute
  '/_user/friends/': typeof UserFriendsIndexRoute
  '/_user/learn/': typeof UserLearnIndexRoute
  '/_user/profile/': typeof UserProfileIndexRoute
  '/_user/admin/$lang/phrases': typeof UserAdminLangPhrasesRouteWithChildren
  '/_user/admin/$lang/requests': typeof UserAdminLangRequestsRouteWithChildren
  '/_user/friends/chats/$friendUid': typeof UserFriendsChatsFriendUidRouteWithChildren
  '/_user/learn/$lang/bulk-add': typeof UserLearnLangBulkAddRoute
  '/_user/learn/$lang/contributions': typeof UserLearnLangContributionsRoute
  '/_user/learn/$lang/deck-settings': typeof UserLearnLangDeckSettingsRoute
  '/_user/learn/$lang/feed': typeof UserLearnLangFeedRoute
  '/_user/learn/$lang/manage-deck': typeof UserLearnLangManageDeckRoute
  '/_user/learn/$lang/playlists': typeof UserLearnLangPlaylistsRouteWithChildren
  '/_user/learn/$lang/review': typeof UserLearnLangReviewRouteWithChildren
  '/_user/learn/$lang/stats': typeof UserLearnLangStatsRoute
  '/_user/learn/browse/charts': typeof UserLearnBrowseChartsRoute
  '/_user/admin/$lang/': typeof UserAdminLangIndexRoute
  '/_user/friends/chats/': typeof UserFriendsChatsIndexRoute
  '/_user/learn/$lang/': typeof UserLearnLangIndexRoute
  '/_user/learn/browse/': typeof UserLearnBrowseIndexRoute
  '/_user/admin/$lang/phrases/$id': typeof UserAdminLangPhrasesIdRoute
  '/_user/admin/$lang/requests/$id': typeof UserAdminLangRequestsIdRoute
  '/_user/friends/chats/$friendUid/recommend': typeof UserFriendsChatsFriendUidRecommendRoute
  '/_user/learn/$lang/phrases/$id': typeof UserLearnLangPhrasesIdRoute
  '/_user/learn/$lang/phrases/new': typeof UserLearnLangPhrasesNewRoute
  '/_user/learn/$lang/playlists/$playlistId': typeof UserLearnLangPlaylistsPlaylistIdRoute
  '/_user/learn/$lang/playlists/new': typeof UserLearnLangPlaylistsNewRoute
  '/_user/learn/$lang/requests/$id': typeof UserLearnLangRequestsIdRoute
  '/_user/learn/$lang/requests/new': typeof UserLearnLangRequestsNewRoute
  '/_user/learn/$lang/review/go': typeof UserLearnLangReviewGoRoute
  '/_user/learn/$lang/review/preview': typeof UserLearnLangReviewPreviewRoute
  '/_user/admin/$lang/phrases/': typeof UserAdminLangPhrasesIndexRoute
  '/_user/admin/$lang/requests/': typeof UserAdminLangRequestsIndexRoute
  '/_user/learn/$lang/playlists/': typeof UserLearnLangPlaylistsIndexRoute
  '/_user/learn/$lang/requests/': typeof UserLearnLangRequestsIndexRoute
  '/_user/learn/$lang/review/': typeof UserLearnLangReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/microcopy'
    | '/privacy-policy'
    | '/request-removal'
    | '/themes'
    | '/forgot-password'
    | '/login'
    | '/set-new-password'
    | '/signup'
    | '/accept-invite'
    | '/admin'
    | '/friends'
    | '/getting-started'
    | '/learn'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/welcome'
    | '/admin/$lang'
    | '/friends/$uid'
    | '/friends/chats'
    | '/learn/$lang'
    | '/learn/add-deck'
    | '/learn/archived'
    | '/learn/browse'
    | '/learn/contributions'
    | '/profile/change-email'
    | '/profile/change-email-confirm'
    | '/profile/change-password'
    | '/friends/invite'
    | '/admin/'
    | '/friends/'
    | '/learn/'
    | '/profile/'
    | '/admin/$lang/phrases'
    | '/admin/$lang/requests'
    | '/friends/chats/$friendUid'
    | '/learn/$lang/bulk-add'
    | '/learn/$lang/contributions'
    | '/learn/$lang/deck-settings'
    | '/learn/$lang/feed'
    | '/learn/$lang/manage-deck'
    | '/learn/$lang/playlists'
    | '/learn/$lang/review'
    | '/learn/$lang/stats'
    | '/learn/browse/charts'
    | '/admin/$lang/'
    | '/friends/chats/'
    | '/learn/$lang/'
    | '/learn/browse/'
    | '/admin/$lang/phrases/$id'
    | '/admin/$lang/requests/$id'
    | '/friends/chats/$friendUid/recommend'
    | '/learn/$lang/phrases/$id'
    | '/learn/$lang/phrases/new'
    | '/learn/$lang/playlists/$playlistId'
    | '/learn/$lang/playlists/new'
    | '/learn/$lang/requests/$id'
    | '/learn/$lang/requests/new'
    | '/learn/$lang/review/go'
    | '/learn/$lang/review/preview'
    | '/admin/$lang/phrases/'
    | '/admin/$lang/requests/'
    | '/learn/$lang/playlists/'
    | '/learn/$lang/requests/'
    | '/learn/$lang/review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/microcopy'
    | '/privacy-policy'
    | '/request-removal'
    | '/themes'
    | '/forgot-password'
    | '/login'
    | '/set-new-password'
    | '/signup'
    | '/accept-invite'
    | '/getting-started'
    | '/notifications'
    | '/search'
    | '/welcome'
    | '/friends/$uid'
    | '/learn/add-deck'
    | '/learn/archived'
    | '/learn/contributions'
    | '/profile/change-email'
    | '/profile/change-email-confirm'
    | '/profile/change-password'
    | '/friends/invite'
    | '/admin'
    | '/friends'
    | '/learn'
    | '/profile'
    | '/friends/chats/$friendUid'
    | '/learn/$lang/bulk-add'
    | '/learn/$lang/contributions'
    | '/learn/$lang/deck-settings'
    | '/learn/$lang/feed'
    | '/learn/$lang/manage-deck'
    | '/learn/$lang/stats'
    | '/learn/browse/charts'
    | '/admin/$lang'
    | '/friends/chats'
    | '/learn/$lang'
    | '/learn/browse'
    | '/admin/$lang/phrases/$id'
    | '/admin/$lang/requests/$id'
    | '/friends/chats/$friendUid/recommend'
    | '/learn/$lang/phrases/$id'
    | '/learn/$lang/phrases/new'
    | '/learn/$lang/playlists/$playlistId'
    | '/learn/$lang/playlists/new'
    | '/learn/$lang/requests/$id'
    | '/learn/$lang/requests/new'
    | '/learn/$lang/review/go'
    | '/learn/$lang/review/preview'
    | '/admin/$lang/phrases'
    | '/admin/$lang/requests'
    | '/learn/$lang/playlists'
    | '/learn/$lang/requests'
    | '/learn/$lang/review'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_user'
    | '/components'
    | '/microcopy'
    | '/privacy-policy'
    | '/request-removal'
    | '/themes'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/set-new-password'
    | '/_auth/signup'
    | '/_user/accept-invite'
    | '/_user/admin'
    | '/_user/friends'
    | '/_user/getting-started'
    | '/_user/learn'
    | '/_user/notifications'
    | '/_user/profile'
    | '/_user/search'
    | '/_user/welcome'
    | '/_user/admin/$lang'
    | '/_user/friends/$uid'
    | '/_user/friends/chats'
    | '/_user/learn/$lang'
    | '/_user/learn/add-deck'
    | '/_user/learn/archived'
    | '/_user/learn/browse'
    | '/_user/learn/contributions'
    | '/_user/profile/change-email'
    | '/_user/profile/change-email-confirm'
    | '/_user/profile/change-password'
    | '/_user/friends/invite'
    | '/_user/admin/'
    | '/_user/friends/'
    | '/_user/learn/'
    | '/_user/profile/'
    | '/_user/admin/$lang/phrases'
    | '/_user/admin/$lang/requests'
    | '/_user/friends/chats/$friendUid'
    | '/_user/learn/$lang/bulk-add'
    | '/_user/learn/$lang/contributions'
    | '/_user/learn/$lang/deck-settings'
    | '/_user/learn/$lang/feed'
    | '/_user/learn/$lang/manage-deck'
    | '/_user/learn/$lang/playlists'
    | '/_user/learn/$lang/review'
    | '/_user/learn/$lang/stats'
    | '/_user/learn/browse/charts'
    | '/_user/admin/$lang/'
    | '/_user/friends/chats/'
    | '/_user/learn/$lang/'
    | '/_user/learn/browse/'
    | '/_user/admin/$lang/phrases/$id'
    | '/_user/admin/$lang/requests/$id'
    | '/_user/friends/chats/$friendUid/recommend'
    | '/_user/learn/$lang/phrases/$id'
    | '/_user/learn/$lang/phrases/new'
    | '/_user/learn/$lang/playlists/$playlistId'
    | '/_user/learn/$lang/playlists/new'
    | '/_user/learn/$lang/requests/$id'
    | '/_user/learn/$lang/requests/new'
    | '/_user/learn/$lang/review/go'
    | '/_user/learn/$lang/review/preview'
    | '/_user/admin/$lang/phrases/'
    | '/_user/admin/$lang/requests/'
    | '/_user/learn/$lang/playlists/'
    | '/_user/learn/$lang/requests/'
    | '/_user/learn/$lang/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  ComponentsLazyRoute: typeof ComponentsLazyRoute
  MicrocopyLazyRoute: typeof MicrocopyLazyRoute
  PrivacyPolicyLazyRoute: typeof PrivacyPolicyLazyRoute
  RequestRemovalLazyRoute: typeof RequestRemovalLazyRoute
  ThemesLazyRoute: typeof ThemesLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-removal': {
      id: '/request-removal'
      path: '/request-removal'
      fullPath: '/request-removal'
      preLoaderRoute: typeof RequestRemovalLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microcopy': {
      id: '/microcopy'
      path: '/microcopy'
      fullPath: '/microcopy'
      preLoaderRoute: typeof MicrocopyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/welcome': {
      id: '/_user/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof UserWelcomeRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/search': {
      id: '/_user/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof UserSearchRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/profile': {
      id: '/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/notifications': {
      id: '/_user/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof UserNotificationsRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/learn': {
      id: '/_user/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof UserLearnRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/getting-started': {
      id: '/_user/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof UserGettingStartedRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/friends': {
      id: '/_user/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof UserFriendsRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/admin': {
      id: '/_user/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof UserAdminRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/accept-invite': {
      id: '/_user/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof UserAcceptInviteRouteImport
      parentRoute: typeof UserRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/set-new-password': {
      id: '/_auth/set-new-password'
      path: '/set-new-password'
      fullPath: '/set-new-password'
      preLoaderRoute: typeof AuthSetNewPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_user/profile/': {
      id: '/_user/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof UserProfileIndexRouteImport
      parentRoute: typeof UserProfileRoute
    }
    '/_user/learn/': {
      id: '/_user/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof UserLearnIndexRouteImport
      parentRoute: typeof UserLearnRoute
    }
    '/_user/friends/': {
      id: '/_user/friends/'
      path: '/'
      fullPath: '/friends/'
      preLoaderRoute: typeof UserFriendsIndexRouteImport
      parentRoute: typeof UserFriendsRoute
    }
    '/_user/admin/': {
      id: '/_user/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof UserAdminIndexRouteImport
      parentRoute: typeof UserAdminRoute
    }
    '/_user/friends/invite': {
      id: '/_user/friends/invite'
      path: '/invite'
      fullPath: '/friends/invite'
      preLoaderRoute: typeof UserFriendsInviteLazyRouteImport
      parentRoute: typeof UserFriendsRoute
    }
    '/_user/profile/change-password': {
      id: '/_user/profile/change-password'
      path: '/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof UserProfileChangePasswordRouteImport
      parentRoute: typeof UserProfileRoute
    }
    '/_user/profile/change-email-confirm': {
      id: '/_user/profile/change-email-confirm'
      path: '/change-email-confirm'
      fullPath: '/profile/change-email-confirm'
      preLoaderRoute: typeof UserProfileChangeEmailConfirmRouteImport
      parentRoute: typeof UserProfileRoute
    }
    '/_user/profile/change-email': {
      id: '/_user/profile/change-email'
      path: '/change-email'
      fullPath: '/profile/change-email'
      preLoaderRoute: typeof UserProfileChangeEmailRouteImport
      parentRoute: typeof UserProfileRoute
    }
    '/_user/learn/contributions': {
      id: '/_user/learn/contributions'
      path: '/contributions'
      fullPath: '/learn/contributions'
      preLoaderRoute: typeof UserLearnContributionsRouteImport
      parentRoute: typeof UserLearnRoute
    }
    '/_user/learn/browse': {
      id: '/_user/learn/browse'
      path: '/browse'
      fullPath: '/learn/browse'
      preLoaderRoute: typeof UserLearnBrowseRouteImport
      parentRoute: typeof UserLearnRoute
    }
    '/_user/learn/archived': {
      id: '/_user/learn/archived'
      path: '/archived'
      fullPath: '/learn/archived'
      preLoaderRoute: typeof UserLearnArchivedRouteImport
      parentRoute: typeof UserLearnRoute
    }
    '/_user/learn/add-deck': {
      id: '/_user/learn/add-deck'
      path: '/add-deck'
      fullPath: '/learn/add-deck'
      preLoaderRoute: typeof UserLearnAddDeckRouteImport
      parentRoute: typeof UserLearnRoute
    }
    '/_user/learn/$lang': {
      id: '/_user/learn/$lang'
      path: '/$lang'
      fullPath: '/learn/$lang'
      preLoaderRoute: typeof UserLearnLangRouteImport
      parentRoute: typeof UserLearnRoute
    }
    '/_user/friends/chats': {
      id: '/_user/friends/chats'
      path: '/chats'
      fullPath: '/friends/chats'
      preLoaderRoute: typeof UserFriendsChatsRouteImport
      parentRoute: typeof UserFriendsRoute
    }
    '/_user/friends/$uid': {
      id: '/_user/friends/$uid'
      path: '/$uid'
      fullPath: '/friends/$uid'
      preLoaderRoute: typeof UserFriendsUidRouteImport
      parentRoute: typeof UserFriendsRoute
    }
    '/_user/admin/$lang': {
      id: '/_user/admin/$lang'
      path: '/$lang'
      fullPath: '/admin/$lang'
      preLoaderRoute: typeof UserAdminLangRouteImport
      parentRoute: typeof UserAdminRoute
    }
    '/_user/learn/browse/': {
      id: '/_user/learn/browse/'
      path: '/'
      fullPath: '/learn/browse/'
      preLoaderRoute: typeof UserLearnBrowseIndexRouteImport
      parentRoute: typeof UserLearnBrowseRoute
    }
    '/_user/learn/$lang/': {
      id: '/_user/learn/$lang/'
      path: '/'
      fullPath: '/learn/$lang/'
      preLoaderRoute: typeof UserLearnLangIndexRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/friends/chats/': {
      id: '/_user/friends/chats/'
      path: '/'
      fullPath: '/friends/chats/'
      preLoaderRoute: typeof UserFriendsChatsIndexRouteImport
      parentRoute: typeof UserFriendsChatsRoute
    }
    '/_user/admin/$lang/': {
      id: '/_user/admin/$lang/'
      path: '/'
      fullPath: '/admin/$lang/'
      preLoaderRoute: typeof UserAdminLangIndexRouteImport
      parentRoute: typeof UserAdminLangRoute
    }
    '/_user/learn/browse/charts': {
      id: '/_user/learn/browse/charts'
      path: '/charts'
      fullPath: '/learn/browse/charts'
      preLoaderRoute: typeof UserLearnBrowseChartsRouteImport
      parentRoute: typeof UserLearnBrowseRoute
    }
    '/_user/learn/$lang/stats': {
      id: '/_user/learn/$lang/stats'
      path: '/stats'
      fullPath: '/learn/$lang/stats'
      preLoaderRoute: typeof UserLearnLangStatsRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/review': {
      id: '/_user/learn/$lang/review'
      path: '/review'
      fullPath: '/learn/$lang/review'
      preLoaderRoute: typeof UserLearnLangReviewRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/playlists': {
      id: '/_user/learn/$lang/playlists'
      path: '/playlists'
      fullPath: '/learn/$lang/playlists'
      preLoaderRoute: typeof UserLearnLangPlaylistsRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/manage-deck': {
      id: '/_user/learn/$lang/manage-deck'
      path: '/manage-deck'
      fullPath: '/learn/$lang/manage-deck'
      preLoaderRoute: typeof UserLearnLangManageDeckRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/feed': {
      id: '/_user/learn/$lang/feed'
      path: '/feed'
      fullPath: '/learn/$lang/feed'
      preLoaderRoute: typeof UserLearnLangFeedRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/deck-settings': {
      id: '/_user/learn/$lang/deck-settings'
      path: '/deck-settings'
      fullPath: '/learn/$lang/deck-settings'
      preLoaderRoute: typeof UserLearnLangDeckSettingsRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/contributions': {
      id: '/_user/learn/$lang/contributions'
      path: '/contributions'
      fullPath: '/learn/$lang/contributions'
      preLoaderRoute: typeof UserLearnLangContributionsRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/bulk-add': {
      id: '/_user/learn/$lang/bulk-add'
      path: '/bulk-add'
      fullPath: '/learn/$lang/bulk-add'
      preLoaderRoute: typeof UserLearnLangBulkAddRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/friends/chats/$friendUid': {
      id: '/_user/friends/chats/$friendUid'
      path: '/$friendUid'
      fullPath: '/friends/chats/$friendUid'
      preLoaderRoute: typeof UserFriendsChatsFriendUidRouteImport
      parentRoute: typeof UserFriendsChatsRoute
    }
    '/_user/admin/$lang/requests': {
      id: '/_user/admin/$lang/requests'
      path: '/requests'
      fullPath: '/admin/$lang/requests'
      preLoaderRoute: typeof UserAdminLangRequestsRouteImport
      parentRoute: typeof UserAdminLangRoute
    }
    '/_user/admin/$lang/phrases': {
      id: '/_user/admin/$lang/phrases'
      path: '/phrases'
      fullPath: '/admin/$lang/phrases'
      preLoaderRoute: typeof UserAdminLangPhrasesRouteImport
      parentRoute: typeof UserAdminLangRoute
    }
    '/_user/learn/$lang/review/': {
      id: '/_user/learn/$lang/review/'
      path: '/'
      fullPath: '/learn/$lang/review/'
      preLoaderRoute: typeof UserLearnLangReviewIndexRouteImport
      parentRoute: typeof UserLearnLangReviewRoute
    }
    '/_user/learn/$lang/requests/': {
      id: '/_user/learn/$lang/requests/'
      path: '/requests'
      fullPath: '/learn/$lang/requests/'
      preLoaderRoute: typeof UserLearnLangRequestsIndexRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/playlists/': {
      id: '/_user/learn/$lang/playlists/'
      path: '/'
      fullPath: '/learn/$lang/playlists/'
      preLoaderRoute: typeof UserLearnLangPlaylistsIndexRouteImport
      parentRoute: typeof UserLearnLangPlaylistsRoute
    }
    '/_user/admin/$lang/requests/': {
      id: '/_user/admin/$lang/requests/'
      path: '/'
      fullPath: '/admin/$lang/requests/'
      preLoaderRoute: typeof UserAdminLangRequestsIndexRouteImport
      parentRoute: typeof UserAdminLangRequestsRoute
    }
    '/_user/admin/$lang/phrases/': {
      id: '/_user/admin/$lang/phrases/'
      path: '/'
      fullPath: '/admin/$lang/phrases/'
      preLoaderRoute: typeof UserAdminLangPhrasesIndexRouteImport
      parentRoute: typeof UserAdminLangPhrasesRoute
    }
    '/_user/learn/$lang/review/preview': {
      id: '/_user/learn/$lang/review/preview'
      path: '/preview'
      fullPath: '/learn/$lang/review/preview'
      preLoaderRoute: typeof UserLearnLangReviewPreviewRouteImport
      parentRoute: typeof UserLearnLangReviewRoute
    }
    '/_user/learn/$lang/review/go': {
      id: '/_user/learn/$lang/review/go'
      path: '/go'
      fullPath: '/learn/$lang/review/go'
      preLoaderRoute: typeof UserLearnLangReviewGoRouteImport
      parentRoute: typeof UserLearnLangReviewRoute
    }
    '/_user/learn/$lang/requests/new': {
      id: '/_user/learn/$lang/requests/new'
      path: '/requests/new'
      fullPath: '/learn/$lang/requests/new'
      preLoaderRoute: typeof UserLearnLangRequestsNewRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/requests/$id': {
      id: '/_user/learn/$lang/requests/$id'
      path: '/requests/$id'
      fullPath: '/learn/$lang/requests/$id'
      preLoaderRoute: typeof UserLearnLangRequestsIdRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/playlists/new': {
      id: '/_user/learn/$lang/playlists/new'
      path: '/new'
      fullPath: '/learn/$lang/playlists/new'
      preLoaderRoute: typeof UserLearnLangPlaylistsNewRouteImport
      parentRoute: typeof UserLearnLangPlaylistsRoute
    }
    '/_user/learn/$lang/playlists/$playlistId': {
      id: '/_user/learn/$lang/playlists/$playlistId'
      path: '/$playlistId'
      fullPath: '/learn/$lang/playlists/$playlistId'
      preLoaderRoute: typeof UserLearnLangPlaylistsPlaylistIdRouteImport
      parentRoute: typeof UserLearnLangPlaylistsRoute
    }
    '/_user/learn/$lang/phrases/new': {
      id: '/_user/learn/$lang/phrases/new'
      path: '/phrases/new'
      fullPath: '/learn/$lang/phrases/new'
      preLoaderRoute: typeof UserLearnLangPhrasesNewRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/phrases/$id': {
      id: '/_user/learn/$lang/phrases/$id'
      path: '/phrases/$id'
      fullPath: '/learn/$lang/phrases/$id'
      preLoaderRoute: typeof UserLearnLangPhrasesIdRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/friends/chats/$friendUid/recommend': {
      id: '/_user/friends/chats/$friendUid/recommend'
      path: '/recommend'
      fullPath: '/friends/chats/$friendUid/recommend'
      preLoaderRoute: typeof UserFriendsChatsFriendUidRecommendRouteImport
      parentRoute: typeof UserFriendsChatsFriendUidRoute
    }
    '/_user/admin/$lang/requests/$id': {
      id: '/_user/admin/$lang/requests/$id'
      path: '/$id'
      fullPath: '/admin/$lang/requests/$id'
      preLoaderRoute: typeof UserAdminLangRequestsIdRouteImport
      parentRoute: typeof UserAdminLangRequestsRoute
    }
    '/_user/admin/$lang/phrases/$id': {
      id: '/_user/admin/$lang/phrases/$id'
      path: '/$id'
      fullPath: '/admin/$lang/phrases/$id'
      preLoaderRoute: typeof UserAdminLangPhrasesIdRouteImport
      parentRoute: typeof UserAdminLangPhrasesRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSetNewPasswordRoute: typeof AuthSetNewPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSetNewPasswordRoute: AuthSetNewPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface UserAdminLangPhrasesRouteChildren {
  UserAdminLangPhrasesIdRoute: typeof UserAdminLangPhrasesIdRoute
  UserAdminLangPhrasesIndexRoute: typeof UserAdminLangPhrasesIndexRoute
}

const UserAdminLangPhrasesRouteChildren: UserAdminLangPhrasesRouteChildren = {
  UserAdminLangPhrasesIdRoute: UserAdminLangPhrasesIdRoute,
  UserAdminLangPhrasesIndexRoute: UserAdminLangPhrasesIndexRoute,
}

const UserAdminLangPhrasesRouteWithChildren =
  UserAdminLangPhrasesRoute._addFileChildren(UserAdminLangPhrasesRouteChildren)

interface UserAdminLangRequestsRouteChildren {
  UserAdminLangRequestsIdRoute: typeof UserAdminLangRequestsIdRoute
  UserAdminLangRequestsIndexRoute: typeof UserAdminLangRequestsIndexRoute
}

const UserAdminLangRequestsRouteChildren: UserAdminLangRequestsRouteChildren = {
  UserAdminLangRequestsIdRoute: UserAdminLangRequestsIdRoute,
  UserAdminLangRequestsIndexRoute: UserAdminLangRequestsIndexRoute,
}

const UserAdminLangRequestsRouteWithChildren =
  UserAdminLangRequestsRoute._addFileChildren(
    UserAdminLangRequestsRouteChildren,
  )

interface UserAdminLangRouteChildren {
  UserAdminLangPhrasesRoute: typeof UserAdminLangPhrasesRouteWithChildren
  UserAdminLangRequestsRoute: typeof UserAdminLangRequestsRouteWithChildren
  UserAdminLangIndexRoute: typeof UserAdminLangIndexRoute
}

const UserAdminLangRouteChildren: UserAdminLangRouteChildren = {
  UserAdminLangPhrasesRoute: UserAdminLangPhrasesRouteWithChildren,
  UserAdminLangRequestsRoute: UserAdminLangRequestsRouteWithChildren,
  UserAdminLangIndexRoute: UserAdminLangIndexRoute,
}

const UserAdminLangRouteWithChildren = UserAdminLangRoute._addFileChildren(
  UserAdminLangRouteChildren,
)

interface UserAdminRouteChildren {
  UserAdminLangRoute: typeof UserAdminLangRouteWithChildren
  UserAdminIndexRoute: typeof UserAdminIndexRoute
}

const UserAdminRouteChildren: UserAdminRouteChildren = {
  UserAdminLangRoute: UserAdminLangRouteWithChildren,
  UserAdminIndexRoute: UserAdminIndexRoute,
}

const UserAdminRouteWithChildren = UserAdminRoute._addFileChildren(
  UserAdminRouteChildren,
)

interface UserFriendsChatsFriendUidRouteChildren {
  UserFriendsChatsFriendUidRecommendRoute: typeof UserFriendsChatsFriendUidRecommendRoute
}

const UserFriendsChatsFriendUidRouteChildren: UserFriendsChatsFriendUidRouteChildren =
  {
    UserFriendsChatsFriendUidRecommendRoute:
      UserFriendsChatsFriendUidRecommendRoute,
  }

const UserFriendsChatsFriendUidRouteWithChildren =
  UserFriendsChatsFriendUidRoute._addFileChildren(
    UserFriendsChatsFriendUidRouteChildren,
  )

interface UserFriendsChatsRouteChildren {
  UserFriendsChatsFriendUidRoute: typeof UserFriendsChatsFriendUidRouteWithChildren
  UserFriendsChatsIndexRoute: typeof UserFriendsChatsIndexRoute
}

const UserFriendsChatsRouteChildren: UserFriendsChatsRouteChildren = {
  UserFriendsChatsFriendUidRoute: UserFriendsChatsFriendUidRouteWithChildren,
  UserFriendsChatsIndexRoute: UserFriendsChatsIndexRoute,
}

const UserFriendsChatsRouteWithChildren =
  UserFriendsChatsRoute._addFileChildren(UserFriendsChatsRouteChildren)

interface UserFriendsRouteChildren {
  UserFriendsUidRoute: typeof UserFriendsUidRoute
  UserFriendsChatsRoute: typeof UserFriendsChatsRouteWithChildren
  UserFriendsInviteLazyRoute: typeof UserFriendsInviteLazyRoute
  UserFriendsIndexRoute: typeof UserFriendsIndexRoute
}

const UserFriendsRouteChildren: UserFriendsRouteChildren = {
  UserFriendsUidRoute: UserFriendsUidRoute,
  UserFriendsChatsRoute: UserFriendsChatsRouteWithChildren,
  UserFriendsInviteLazyRoute: UserFriendsInviteLazyRoute,
  UserFriendsIndexRoute: UserFriendsIndexRoute,
}

const UserFriendsRouteWithChildren = UserFriendsRoute._addFileChildren(
  UserFriendsRouteChildren,
)

interface UserLearnLangPlaylistsRouteChildren {
  UserLearnLangPlaylistsPlaylistIdRoute: typeof UserLearnLangPlaylistsPlaylistIdRoute
  UserLearnLangPlaylistsNewRoute: typeof UserLearnLangPlaylistsNewRoute
  UserLearnLangPlaylistsIndexRoute: typeof UserLearnLangPlaylistsIndexRoute
}

const UserLearnLangPlaylistsRouteChildren: UserLearnLangPlaylistsRouteChildren =
  {
    UserLearnLangPlaylistsPlaylistIdRoute:
      UserLearnLangPlaylistsPlaylistIdRoute,
    UserLearnLangPlaylistsNewRoute: UserLearnLangPlaylistsNewRoute,
    UserLearnLangPlaylistsIndexRoute: UserLearnLangPlaylistsIndexRoute,
  }

const UserLearnLangPlaylistsRouteWithChildren =
  UserLearnLangPlaylistsRoute._addFileChildren(
    UserLearnLangPlaylistsRouteChildren,
  )

interface UserLearnLangReviewRouteChildren {
  UserLearnLangReviewGoRoute: typeof UserLearnLangReviewGoRoute
  UserLearnLangReviewPreviewRoute: typeof UserLearnLangReviewPreviewRoute
  UserLearnLangReviewIndexRoute: typeof UserLearnLangReviewIndexRoute
}

const UserLearnLangReviewRouteChildren: UserLearnLangReviewRouteChildren = {
  UserLearnLangReviewGoRoute: UserLearnLangReviewGoRoute,
  UserLearnLangReviewPreviewRoute: UserLearnLangReviewPreviewRoute,
  UserLearnLangReviewIndexRoute: UserLearnLangReviewIndexRoute,
}

const UserLearnLangReviewRouteWithChildren =
  UserLearnLangReviewRoute._addFileChildren(UserLearnLangReviewRouteChildren)

interface UserLearnLangRouteChildren {
  UserLearnLangBulkAddRoute: typeof UserLearnLangBulkAddRoute
  UserLearnLangContributionsRoute: typeof UserLearnLangContributionsRoute
  UserLearnLangDeckSettingsRoute: typeof UserLearnLangDeckSettingsRoute
  UserLearnLangFeedRoute: typeof UserLearnLangFeedRoute
  UserLearnLangManageDeckRoute: typeof UserLearnLangManageDeckRoute
  UserLearnLangPlaylistsRoute: typeof UserLearnLangPlaylistsRouteWithChildren
  UserLearnLangReviewRoute: typeof UserLearnLangReviewRouteWithChildren
  UserLearnLangStatsRoute: typeof UserLearnLangStatsRoute
  UserLearnLangIndexRoute: typeof UserLearnLangIndexRoute
  UserLearnLangPhrasesIdRoute: typeof UserLearnLangPhrasesIdRoute
  UserLearnLangPhrasesNewRoute: typeof UserLearnLangPhrasesNewRoute
  UserLearnLangRequestsIdRoute: typeof UserLearnLangRequestsIdRoute
  UserLearnLangRequestsNewRoute: typeof UserLearnLangRequestsNewRoute
  UserLearnLangRequestsIndexRoute: typeof UserLearnLangRequestsIndexRoute
}

const UserLearnLangRouteChildren: UserLearnLangRouteChildren = {
  UserLearnLangBulkAddRoute: UserLearnLangBulkAddRoute,
  UserLearnLangContributionsRoute: UserLearnLangContributionsRoute,
  UserLearnLangDeckSettingsRoute: UserLearnLangDeckSettingsRoute,
  UserLearnLangFeedRoute: UserLearnLangFeedRoute,
  UserLearnLangManageDeckRoute: UserLearnLangManageDeckRoute,
  UserLearnLangPlaylistsRoute: UserLearnLangPlaylistsRouteWithChildren,
  UserLearnLangReviewRoute: UserLearnLangReviewRouteWithChildren,
  UserLearnLangStatsRoute: UserLearnLangStatsRoute,
  UserLearnLangIndexRoute: UserLearnLangIndexRoute,
  UserLearnLangPhrasesIdRoute: UserLearnLangPhrasesIdRoute,
  UserLearnLangPhrasesNewRoute: UserLearnLangPhrasesNewRoute,
  UserLearnLangRequestsIdRoute: UserLearnLangRequestsIdRoute,
  UserLearnLangRequestsNewRoute: UserLearnLangRequestsNewRoute,
  UserLearnLangRequestsIndexRoute: UserLearnLangRequestsIndexRoute,
}

const UserLearnLangRouteWithChildren = UserLearnLangRoute._addFileChildren(
  UserLearnLangRouteChildren,
)

interface UserLearnBrowseRouteChildren {
  UserLearnBrowseChartsRoute: typeof UserLearnBrowseChartsRoute
  UserLearnBrowseIndexRoute: typeof UserLearnBrowseIndexRoute
}

const UserLearnBrowseRouteChildren: UserLearnBrowseRouteChildren = {
  UserLearnBrowseChartsRoute: UserLearnBrowseChartsRoute,
  UserLearnBrowseIndexRoute: UserLearnBrowseIndexRoute,
}

const UserLearnBrowseRouteWithChildren = UserLearnBrowseRoute._addFileChildren(
  UserLearnBrowseRouteChildren,
)

interface UserLearnRouteChildren {
  UserLearnLangRoute: typeof UserLearnLangRouteWithChildren
  UserLearnAddDeckRoute: typeof UserLearnAddDeckRoute
  UserLearnArchivedRoute: typeof UserLearnArchivedRoute
  UserLearnBrowseRoute: typeof UserLearnBrowseRouteWithChildren
  UserLearnContributionsRoute: typeof UserLearnContributionsRoute
  UserLearnIndexRoute: typeof UserLearnIndexRoute
}

const UserLearnRouteChildren: UserLearnRouteChildren = {
  UserLearnLangRoute: UserLearnLangRouteWithChildren,
  UserLearnAddDeckRoute: UserLearnAddDeckRoute,
  UserLearnArchivedRoute: UserLearnArchivedRoute,
  UserLearnBrowseRoute: UserLearnBrowseRouteWithChildren,
  UserLearnContributionsRoute: UserLearnContributionsRoute,
  UserLearnIndexRoute: UserLearnIndexRoute,
}

const UserLearnRouteWithChildren = UserLearnRoute._addFileChildren(
  UserLearnRouteChildren,
)

interface UserProfileRouteChildren {
  UserProfileChangeEmailRoute: typeof UserProfileChangeEmailRoute
  UserProfileChangeEmailConfirmRoute: typeof UserProfileChangeEmailConfirmRoute
  UserProfileChangePasswordRoute: typeof UserProfileChangePasswordRoute
  UserProfileIndexRoute: typeof UserProfileIndexRoute
}

const UserProfileRouteChildren: UserProfileRouteChildren = {
  UserProfileChangeEmailRoute: UserProfileChangeEmailRoute,
  UserProfileChangeEmailConfirmRoute: UserProfileChangeEmailConfirmRoute,
  UserProfileChangePasswordRoute: UserProfileChangePasswordRoute,
  UserProfileIndexRoute: UserProfileIndexRoute,
}

const UserProfileRouteWithChildren = UserProfileRoute._addFileChildren(
  UserProfileRouteChildren,
)

interface UserRouteChildren {
  UserAcceptInviteRoute: typeof UserAcceptInviteRoute
  UserAdminRoute: typeof UserAdminRouteWithChildren
  UserFriendsRoute: typeof UserFriendsRouteWithChildren
  UserGettingStartedRoute: typeof UserGettingStartedRoute
  UserLearnRoute: typeof UserLearnRouteWithChildren
  UserNotificationsRoute: typeof UserNotificationsRoute
  UserProfileRoute: typeof UserProfileRouteWithChildren
  UserSearchRoute: typeof UserSearchRoute
  UserWelcomeRoute: typeof UserWelcomeRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserAcceptInviteRoute: UserAcceptInviteRoute,
  UserAdminRoute: UserAdminRouteWithChildren,
  UserFriendsRoute: UserFriendsRouteWithChildren,
  UserGettingStartedRoute: UserGettingStartedRoute,
  UserLearnRoute: UserLearnRouteWithChildren,
  UserNotificationsRoute: UserNotificationsRoute,
  UserProfileRoute: UserProfileRouteWithChildren,
  UserSearchRoute: UserSearchRoute,
  UserWelcomeRoute: UserWelcomeRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  ComponentsLazyRoute: ComponentsLazyRoute,
  MicrocopyLazyRoute: MicrocopyLazyRoute,
  PrivacyPolicyLazyRoute: PrivacyPolicyLazyRoute,
  RequestRemovalLazyRoute: RequestRemovalLazyRoute,
  ThemesLazyRoute: ThemesLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
