/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/_user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserWelcomeRouteImport } from './routes/_user/welcome'
import { Route as UserSearchRouteImport } from './routes/_user/search'
import { Route as UserProfileRouteImport } from './routes/_user/profile'
import { Route as UserNotificationsRouteImport } from './routes/_user/notifications'
import { Route as UserLearnRouteImport } from './routes/_user/learn'
import { Route as UserGettingStartedRouteImport } from './routes/_user/getting-started'
import { Route as UserFriendsRouteImport } from './routes/_user/friends'
import { Route as UserBrowseRouteImport } from './routes/_user/browse'
import { Route as UserAcceptInviteRouteImport } from './routes/_user/accept-invite'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as UserLearnIndexRouteImport } from './routes/_user/learn/index'
import { Route as UserFriendsIndexRouteImport } from './routes/_user/friends/index'
import { Route as UserBrowseIndexRouteImport } from './routes/_user/browse.index'
import { Route as UserAdminIndexRouteImport } from './routes/_user/admin/index'
import { Route as UserProfileChangeEmailConfirmRouteImport } from './routes/_user/profile/change-email-confirm'
import { Route as UserLearnContributionsRouteImport } from './routes/_user/learn/contributions'
import { Route as UserLearnAddDeckRouteImport } from './routes/_user/learn/add-deck'
import { Route as UserLearnLangRouteImport } from './routes/_user/learn/$lang'
import { Route as UserFriendsChatsRouteImport } from './routes/_user/friends/chats'
import { Route as UserFriendsUidRouteImport } from './routes/_user/friends/$uid'
import { Route as UserBrowseChartsRouteImport } from './routes/_user/browse.charts'
import { Route as UserAdminLangRouteImport } from './routes/_user/admin/$lang'
import { Route as UserLearnLangIndexRouteImport } from './routes/_user/learn/$lang.index'
import { Route as UserAdminLangIndexRouteImport } from './routes/_user/admin/$lang.index'
import { Route as UserLearnLangReviewRouteImport } from './routes/_user/learn/$lang.review'
import { Route as UserLearnLangPlaylistsRouteImport } from './routes/_user/learn/$lang.playlists'
import { Route as UserLearnLangFeedRouteImport } from './routes/_user/learn/$lang.feed'
import { Route as UserLearnLangContributionsRouteImport } from './routes/_user/learn/$lang.contributions'
import { Route as UserLearnLangBulkAddRouteImport } from './routes/_user/learn/$lang.bulk-add'
import { Route as UserFriendsChatsFriendUidRouteImport } from './routes/_user/friends/chats.$friendUid'
import { Route as UserAdminLangRequestsRouteImport } from './routes/_user/admin/$lang.requests'
import { Route as UserAdminLangPhrasesRouteImport } from './routes/_user/admin/$lang.phrases'
import { Route as UserLearnLangReviewIndexRouteImport } from './routes/_user/learn/$lang.review.index'
import { Route as UserLearnLangRequestsIndexRouteImport } from './routes/_user/learn/$lang.requests.index'
import { Route as UserLearnLangReviewPreviewRouteImport } from './routes/_user/learn/$lang.review.preview'
import { Route as UserLearnLangReviewGoRouteImport } from './routes/_user/learn/$lang.review.go'
import { Route as UserLearnLangRequestsNewRouteImport } from './routes/_user/learn/$lang.requests.new'
import { Route as UserLearnLangRequestsIdRouteImport } from './routes/_user/learn/$lang.requests.$id'
import { Route as UserLearnLangPlaylistsNewRouteImport } from './routes/_user/learn/$lang.playlists.new'
import { Route as UserLearnLangPlaylistsPlaylistIdRouteImport } from './routes/_user/learn/$lang.playlists.$playlistId'
import { Route as UserLearnLangPhrasesNewRouteImport } from './routes/_user/learn/$lang.phrases.new'
import { Route as UserLearnLangPhrasesIdRouteImport } from './routes/_user/learn/$lang.phrases.$id'

const ThemesLazyRouteImport = createFileRoute('/themes')()
const RequestRemovalLazyRouteImport = createFileRoute('/request-removal')()
const PrivacyPolicyLazyRouteImport = createFileRoute('/privacy-policy')()
const MicrocopyLazyRouteImport = createFileRoute('/microcopy')()
const ComponentsLazyRouteImport = createFileRoute('/components')()
const ChatsLazyRouteImport = createFileRoute('/chats')()
const AuthLazyRouteImport = createFileRoute('/_auth')()
const ChatsIndexLazyRouteImport = createFileRoute('/chats/')()
const ChatsLangLazyRouteImport = createFileRoute('/chats/$lang')()
const UserAdminLazyRouteImport = createFileRoute('/_user/admin')()
const AuthSetNewPasswordLazyRouteImport = createFileRoute(
  '/_auth/set-new-password',
)()
const AuthForgotPasswordLazyRouteImport = createFileRoute(
  '/_auth/forgot-password',
)()
const UserSearchIndexLazyRouteImport = createFileRoute('/_user/search/')()
const UserProfileIndexLazyRouteImport = createFileRoute('/_user/profile/')()
const UserSearchTestLazyRouteImport = createFileRoute('/_user/search/test')()
const UserProfileChangePasswordLazyRouteImport = createFileRoute(
  '/_user/profile/change-password',
)()
const UserProfileChangeEmailLazyRouteImport = createFileRoute(
  '/_user/profile/change-email',
)()
const UserLearnArchivedLazyRouteImport = createFileRoute(
  '/_user/learn/archived',
)()
const UserFriendsInviteLazyRouteImport = createFileRoute(
  '/_user/friends/invite',
)()
const UserFriendsChatsIndexLazyRouteImport = createFileRoute(
  '/_user/friends/chats/',
)()
const UserLearnLangStatsLazyRouteImport = createFileRoute(
  '/_user/learn/$lang/stats',
)()
const UserLearnLangManageDeckLazyRouteImport = createFileRoute(
  '/_user/learn/$lang/manage-deck',
)()
const UserLearnLangDeckSettingsLazyRouteImport = createFileRoute(
  '/_user/learn/$lang/deck-settings',
)()
const UserLearnLangPlaylistsIndexLazyRouteImport = createFileRoute(
  '/_user/learn/$lang/playlists/',
)()
const UserAdminLangRequestsIndexLazyRouteImport = createFileRoute(
  '/_user/admin/$lang/requests/',
)()
const UserAdminLangPhrasesIndexLazyRouteImport = createFileRoute(
  '/_user/admin/$lang/phrases/',
)()
const UserFriendsChatsFriendUidRecommendLazyRouteImport = createFileRoute(
  '/_user/friends/chats/$friendUid/recommend',
)()
const UserAdminLangRequestsIdLazyRouteImport = createFileRoute(
  '/_user/admin/$lang/requests/$id',
)()
const UserAdminLangPhrasesIdLazyRouteImport = createFileRoute(
  '/_user/admin/$lang/phrases/$id',
)()

const ThemesLazyRoute = ThemesLazyRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/themes.lazy').then((d) => d.Route))
const RequestRemovalLazyRoute = RequestRemovalLazyRouteImport.update({
  id: '/request-removal',
  path: '/request-removal',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/request-removal.lazy').then((d) => d.Route),
)
const PrivacyPolicyLazyRoute = PrivacyPolicyLazyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/privacy-policy.lazy').then((d) => d.Route),
)
const MicrocopyLazyRoute = MicrocopyLazyRouteImport.update({
  id: '/microcopy',
  path: '/microcopy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/microcopy.lazy').then((d) => d.Route))
const ComponentsLazyRoute = ComponentsLazyRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/components.lazy').then((d) => d.Route))
const ChatsLazyRoute = ChatsLazyRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/chats.lazy').then((d) => d.Route))
const AuthLazyRoute = AuthLazyRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/_auth.lazy').then((d) => d.Route))
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/_user.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ChatsIndexLazyRoute = ChatsIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatsLazyRoute,
} as any).lazy(() => import('./routes/chats.index.lazy').then((d) => d.Route))
const ChatsLangLazyRoute = ChatsLangLazyRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => ChatsLazyRoute,
} as any).lazy(() => import('./routes/chats.$lang.lazy').then((d) => d.Route))
const UserAdminLazyRoute = UserAdminLazyRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => UserRoute,
} as any).lazy(() => import('./routes/_user/admin.lazy').then((d) => d.Route))
const AuthSetNewPasswordLazyRoute = AuthSetNewPasswordLazyRouteImport.update({
  id: '/set-new-password',
  path: '/set-new-password',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() =>
  import('./routes/_auth/set-new-password.lazy').then((d) => d.Route),
)
const AuthForgotPasswordLazyRoute = AuthForgotPasswordLazyRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() =>
  import('./routes/_auth/forgot-password.lazy').then((d) => d.Route),
)
const UserWelcomeRoute = UserWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => UserRoute,
} as any).lazy(() => import('./routes/_user/welcome.lazy').then((d) => d.Route))
const UserSearchRoute = UserSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => UserRoute,
} as any).lazy(() => import('./routes/_user/search.lazy').then((d) => d.Route))
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserNotificationsRoute = UserNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => UserRoute,
} as any).lazy(() =>
  import('./routes/_user/notifications.lazy').then((d) => d.Route),
)
const UserLearnRoute = UserLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => UserRoute,
} as any).lazy(() => import('./routes/_user/learn.lazy').then((d) => d.Route))
const UserGettingStartedRoute = UserGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => UserRoute,
} as any).lazy(() =>
  import('./routes/_user/getting-started.lazy').then((d) => d.Route),
)
const UserFriendsRoute = UserFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => UserRoute,
} as any).lazy(() => import('./routes/_user/friends.lazy').then((d) => d.Route))
const UserBrowseRoute = UserBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => UserRoute,
} as any)
const UserAcceptInviteRoute = UserAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => UserRoute,
} as any).lazy(() =>
  import('./routes/_user/accept-invite.lazy').then((d) => d.Route),
)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() => import('./routes/_auth/signup.lazy').then((d) => d.Route))
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() => import('./routes/_auth/login.lazy').then((d) => d.Route))
const UserSearchIndexLazyRoute = UserSearchIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserSearchRoute,
} as any).lazy(() =>
  import('./routes/_user/search.index.lazy').then((d) => d.Route),
)
const UserProfileIndexLazyRoute = UserProfileIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserProfileRoute,
} as any).lazy(() =>
  import('./routes/_user/profile/index.lazy').then((d) => d.Route),
)
const UserLearnIndexRoute = UserLearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserLearnRoute,
} as any).lazy(() =>
  import('./routes/_user/learn/index.lazy').then((d) => d.Route),
)
const UserFriendsIndexRoute = UserFriendsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserFriendsRoute,
} as any).lazy(() =>
  import('./routes/_user/friends/index.lazy').then((d) => d.Route),
)
const UserBrowseIndexRoute = UserBrowseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserBrowseRoute,
} as any).lazy(() =>
  import('./routes/_user/browse.index.lazy').then((d) => d.Route),
)
const UserAdminIndexRoute = UserAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserAdminLazyRoute,
} as any).lazy(() =>
  import('./routes/_user/admin/index.lazy').then((d) => d.Route),
)
const UserSearchTestLazyRoute = UserSearchTestLazyRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => UserSearchRoute,
} as any).lazy(() =>
  import('./routes/_user/search.test.lazy').then((d) => d.Route),
)
const UserProfileChangePasswordLazyRoute =
  UserProfileChangePasswordLazyRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => UserProfileRoute,
  } as any).lazy(() =>
    import('./routes/_user/profile/change-password.lazy').then((d) => d.Route),
  )
const UserProfileChangeEmailLazyRoute =
  UserProfileChangeEmailLazyRouteImport.update({
    id: '/change-email',
    path: '/change-email',
    getParentRoute: () => UserProfileRoute,
  } as any).lazy(() =>
    import('./routes/_user/profile/change-email.lazy').then((d) => d.Route),
  )
const UserLearnArchivedLazyRoute = UserLearnArchivedLazyRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => UserLearnRoute,
} as any).lazy(() =>
  import('./routes/_user/learn/archived.lazy').then((d) => d.Route),
)
const UserFriendsInviteLazyRoute = UserFriendsInviteLazyRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => UserFriendsRoute,
} as any).lazy(() =>
  import('./routes/_user/friends/invite.lazy').then((d) => d.Route),
)
const UserProfileChangeEmailConfirmRoute =
  UserProfileChangeEmailConfirmRouteImport.update({
    id: '/change-email-confirm',
    path: '/change-email-confirm',
    getParentRoute: () => UserProfileRoute,
  } as any).lazy(() =>
    import('./routes/_user/profile/change-email-confirm.lazy').then(
      (d) => d.Route,
    ),
  )
const UserLearnContributionsRoute = UserLearnContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => UserLearnRoute,
} as any).lazy(() =>
  import('./routes/_user/learn/contributions.lazy').then((d) => d.Route),
)
const UserLearnAddDeckRoute = UserLearnAddDeckRouteImport.update({
  id: '/add-deck',
  path: '/add-deck',
  getParentRoute: () => UserLearnRoute,
} as any).lazy(() =>
  import('./routes/_user/learn/add-deck.lazy').then((d) => d.Route),
)
const UserLearnLangRoute = UserLearnLangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => UserLearnRoute,
} as any).lazy(() =>
  import('./routes/_user/learn/$lang.lazy').then((d) => d.Route),
)
const UserFriendsChatsRoute = UserFriendsChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => UserFriendsRoute,
} as any).lazy(() =>
  import('./routes/_user/friends/chats.lazy').then((d) => d.Route),
)
const UserFriendsUidRoute = UserFriendsUidRouteImport.update({
  id: '/$uid',
  path: '/$uid',
  getParentRoute: () => UserFriendsRoute,
} as any).lazy(() =>
  import('./routes/_user/friends/$uid.lazy').then((d) => d.Route),
)
const UserBrowseChartsRoute = UserBrowseChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => UserBrowseRoute,
} as any).lazy(() =>
  import('./routes/_user/browse.charts.lazy').then((d) => d.Route),
)
const UserAdminLangRoute = UserAdminLangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => UserAdminLazyRoute,
} as any).lazy(() =>
  import('./routes/_user/admin/$lang.lazy').then((d) => d.Route),
)
const UserFriendsChatsIndexLazyRoute =
  UserFriendsChatsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserFriendsChatsRoute,
  } as any).lazy(() =>
    import('./routes/_user/friends/chats.index.lazy').then((d) => d.Route),
  )
const UserLearnLangIndexRoute = UserLearnLangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserLearnLangRoute,
} as any)
const UserAdminLangIndexRoute = UserAdminLangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserAdminLangRoute,
} as any)
const UserLearnLangStatsLazyRoute = UserLearnLangStatsLazyRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => UserLearnLangRoute,
} as any).lazy(() =>
  import('./routes/_user/learn/$lang.stats.lazy').then((d) => d.Route),
)
const UserLearnLangManageDeckLazyRoute =
  UserLearnLangManageDeckLazyRouteImport.update({
    id: '/manage-deck',
    path: '/manage-deck',
    getParentRoute: () => UserLearnLangRoute,
  } as any).lazy(() =>
    import('./routes/_user/learn/$lang.manage-deck.lazy').then((d) => d.Route),
  )
const UserLearnLangDeckSettingsLazyRoute =
  UserLearnLangDeckSettingsLazyRouteImport.update({
    id: '/deck-settings',
    path: '/deck-settings',
    getParentRoute: () => UserLearnLangRoute,
  } as any).lazy(() =>
    import('./routes/_user/learn/$lang.deck-settings.lazy').then(
      (d) => d.Route,
    ),
  )
const UserLearnLangReviewRoute = UserLearnLangReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => UserLearnLangRoute,
} as any).lazy(() =>
  import('./routes/_user/learn/$lang.review.lazy').then((d) => d.Route),
)
const UserLearnLangPlaylistsRoute = UserLearnLangPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => UserLearnLangRoute,
} as any)
const UserLearnLangFeedRoute = UserLearnLangFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => UserLearnLangRoute,
} as any).lazy(() =>
  import('./routes/_user/learn/$lang.feed.lazy').then((d) => d.Route),
)
const UserLearnLangContributionsRoute =
  UserLearnLangContributionsRouteImport.update({
    id: '/contributions',
    path: '/contributions',
    getParentRoute: () => UserLearnLangRoute,
  } as any).lazy(() =>
    import('./routes/_user/learn/$lang.contributions.lazy').then(
      (d) => d.Route,
    ),
  )
const UserLearnLangBulkAddRoute = UserLearnLangBulkAddRouteImport.update({
  id: '/bulk-add',
  path: '/bulk-add',
  getParentRoute: () => UserLearnLangRoute,
} as any).lazy(() =>
  import('./routes/_user/learn/$lang.bulk-add.lazy').then((d) => d.Route),
)
const UserFriendsChatsFriendUidRoute =
  UserFriendsChatsFriendUidRouteImport.update({
    id: '/$friendUid',
    path: '/$friendUid',
    getParentRoute: () => UserFriendsChatsRoute,
  } as any).lazy(() =>
    import('./routes/_user/friends/chats.$friendUid.lazy').then((d) => d.Route),
  )
const UserAdminLangRequestsRoute = UserAdminLangRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => UserAdminLangRoute,
} as any).lazy(() =>
  import('./routes/_user/admin/$lang.requests.lazy').then((d) => d.Route),
)
const UserAdminLangPhrasesRoute = UserAdminLangPhrasesRouteImport.update({
  id: '/phrases',
  path: '/phrases',
  getParentRoute: () => UserAdminLangRoute,
} as any).lazy(() =>
  import('./routes/_user/admin/$lang.phrases.lazy').then((d) => d.Route),
)
const UserLearnLangPlaylistsIndexLazyRoute =
  UserLearnLangPlaylistsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserLearnLangPlaylistsRoute,
  } as any).lazy(() =>
    import('./routes/_user/learn/$lang.playlists.index.lazy').then(
      (d) => d.Route,
    ),
  )
const UserAdminLangRequestsIndexLazyRoute =
  UserAdminLangRequestsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserAdminLangRequestsRoute,
  } as any).lazy(() =>
    import('./routes/_user/admin/$lang.requests.index.lazy').then(
      (d) => d.Route,
    ),
  )
const UserAdminLangPhrasesIndexLazyRoute =
  UserAdminLangPhrasesIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserAdminLangPhrasesRoute,
  } as any).lazy(() =>
    import('./routes/_user/admin/$lang.phrases.index.lazy').then(
      (d) => d.Route,
    ),
  )
const UserLearnLangReviewIndexRoute =
  UserLearnLangReviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserLearnLangReviewRoute,
  } as any).lazy(() =>
    import('./routes/_user/learn/$lang.review.index.lazy').then((d) => d.Route),
  )
const UserLearnLangRequestsIndexRoute =
  UserLearnLangRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => UserLearnLangRoute,
  } as any)
const UserFriendsChatsFriendUidRecommendLazyRoute =
  UserFriendsChatsFriendUidRecommendLazyRouteImport.update({
    id: '/recommend',
    path: '/recommend',
    getParentRoute: () => UserFriendsChatsFriendUidRoute,
  } as any).lazy(() =>
    import('./routes/_user/friends/chats.$friendUid.recommend.lazy').then(
      (d) => d.Route,
    ),
  )
const UserAdminLangRequestsIdLazyRoute =
  UserAdminLangRequestsIdLazyRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => UserAdminLangRequestsRoute,
  } as any).lazy(() =>
    import('./routes/_user/admin/$lang.requests.$id.lazy').then((d) => d.Route),
  )
const UserAdminLangPhrasesIdLazyRoute =
  UserAdminLangPhrasesIdLazyRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => UserAdminLangPhrasesRoute,
  } as any).lazy(() =>
    import('./routes/_user/admin/$lang.phrases.$id.lazy').then((d) => d.Route),
  )
const UserLearnLangReviewPreviewRoute =
  UserLearnLangReviewPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => UserLearnLangReviewRoute,
  } as any).lazy(() =>
    import('./routes/_user/learn/$lang.review.preview.lazy').then(
      (d) => d.Route,
    ),
  )
const UserLearnLangReviewGoRoute = UserLearnLangReviewGoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => UserLearnLangReviewRoute,
} as any).lazy(() =>
  import('./routes/_user/learn/$lang.review.go.lazy').then((d) => d.Route),
)
const UserLearnLangRequestsNewRoute =
  UserLearnLangRequestsNewRouteImport.update({
    id: '/requests/new',
    path: '/requests/new',
    getParentRoute: () => UserLearnLangRoute,
  } as any).lazy(() =>
    import('./routes/_user/learn/$lang.requests.new.lazy').then((d) => d.Route),
  )
const UserLearnLangRequestsIdRoute = UserLearnLangRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => UserLearnLangRoute,
} as any).lazy(() =>
  import('./routes/_user/learn/$lang.requests.$id.lazy').then((d) => d.Route),
)
const UserLearnLangPlaylistsNewRoute =
  UserLearnLangPlaylistsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => UserLearnLangPlaylistsRoute,
  } as any).lazy(() =>
    import('./routes/_user/learn/$lang.playlists.new.lazy').then(
      (d) => d.Route,
    ),
  )
const UserLearnLangPlaylistsPlaylistIdRoute =
  UserLearnLangPlaylistsPlaylistIdRouteImport.update({
    id: '/$playlistId',
    path: '/$playlistId',
    getParentRoute: () => UserLearnLangPlaylistsRoute,
  } as any).lazy(() =>
    import('./routes/_user/learn/$lang.playlists.$playlistId.lazy').then(
      (d) => d.Route,
    ),
  )
const UserLearnLangPhrasesNewRoute = UserLearnLangPhrasesNewRouteImport.update({
  id: '/phrases/new',
  path: '/phrases/new',
  getParentRoute: () => UserLearnLangRoute,
} as any).lazy(() =>
  import('./routes/_user/learn/$lang.phrases.new.lazy').then((d) => d.Route),
)
const UserLearnLangPhrasesIdRoute = UserLearnLangPhrasesIdRouteImport.update({
  id: '/phrases/$id',
  path: '/phrases/$id',
  getParentRoute: () => UserLearnLangRoute,
} as any).lazy(() =>
  import('./routes/_user/learn/$lang.phrases.$id.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof ChatsLazyRouteWithChildren
  '/components': typeof ComponentsLazyRoute
  '/microcopy': typeof MicrocopyLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/request-removal': typeof RequestRemovalLazyRoute
  '/themes': typeof ThemesLazyRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/accept-invite': typeof UserAcceptInviteRoute
  '/browse': typeof UserBrowseRouteWithChildren
  '/friends': typeof UserFriendsRouteWithChildren
  '/getting-started': typeof UserGettingStartedRoute
  '/learn': typeof UserLearnRouteWithChildren
  '/notifications': typeof UserNotificationsRoute
  '/profile': typeof UserProfileRouteWithChildren
  '/search': typeof UserSearchRouteWithChildren
  '/welcome': typeof UserWelcomeRoute
  '/forgot-password': typeof AuthForgotPasswordLazyRoute
  '/set-new-password': typeof AuthSetNewPasswordLazyRoute
  '/admin': typeof UserAdminLazyRouteWithChildren
  '/chats/$lang': typeof ChatsLangLazyRoute
  '/chats/': typeof ChatsIndexLazyRoute
  '/admin/$lang': typeof UserAdminLangRouteWithChildren
  '/browse/charts': typeof UserBrowseChartsRoute
  '/friends/$uid': typeof UserFriendsUidRoute
  '/friends/chats': typeof UserFriendsChatsRouteWithChildren
  '/learn/$lang': typeof UserLearnLangRouteWithChildren
  '/learn/add-deck': typeof UserLearnAddDeckRoute
  '/learn/contributions': typeof UserLearnContributionsRoute
  '/profile/change-email-confirm': typeof UserProfileChangeEmailConfirmRoute
  '/friends/invite': typeof UserFriendsInviteLazyRoute
  '/learn/archived': typeof UserLearnArchivedLazyRoute
  '/profile/change-email': typeof UserProfileChangeEmailLazyRoute
  '/profile/change-password': typeof UserProfileChangePasswordLazyRoute
  '/search/test': typeof UserSearchTestLazyRoute
  '/admin/': typeof UserAdminIndexRoute
  '/browse/': typeof UserBrowseIndexRoute
  '/friends/': typeof UserFriendsIndexRoute
  '/learn/': typeof UserLearnIndexRoute
  '/profile/': typeof UserProfileIndexLazyRoute
  '/search/': typeof UserSearchIndexLazyRoute
  '/admin/$lang/phrases': typeof UserAdminLangPhrasesRouteWithChildren
  '/admin/$lang/requests': typeof UserAdminLangRequestsRouteWithChildren
  '/friends/chats/$friendUid': typeof UserFriendsChatsFriendUidRouteWithChildren
  '/learn/$lang/bulk-add': typeof UserLearnLangBulkAddRoute
  '/learn/$lang/contributions': typeof UserLearnLangContributionsRoute
  '/learn/$lang/feed': typeof UserLearnLangFeedRoute
  '/learn/$lang/playlists': typeof UserLearnLangPlaylistsRouteWithChildren
  '/learn/$lang/review': typeof UserLearnLangReviewRouteWithChildren
  '/learn/$lang/deck-settings': typeof UserLearnLangDeckSettingsLazyRoute
  '/learn/$lang/manage-deck': typeof UserLearnLangManageDeckLazyRoute
  '/learn/$lang/stats': typeof UserLearnLangStatsLazyRoute
  '/admin/$lang/': typeof UserAdminLangIndexRoute
  '/learn/$lang/': typeof UserLearnLangIndexRoute
  '/friends/chats/': typeof UserFriendsChatsIndexLazyRoute
  '/learn/$lang/phrases/$id': typeof UserLearnLangPhrasesIdRoute
  '/learn/$lang/phrases/new': typeof UserLearnLangPhrasesNewRoute
  '/learn/$lang/playlists/$playlistId': typeof UserLearnLangPlaylistsPlaylistIdRoute
  '/learn/$lang/playlists/new': typeof UserLearnLangPlaylistsNewRoute
  '/learn/$lang/requests/$id': typeof UserLearnLangRequestsIdRoute
  '/learn/$lang/requests/new': typeof UserLearnLangRequestsNewRoute
  '/learn/$lang/review/go': typeof UserLearnLangReviewGoRoute
  '/learn/$lang/review/preview': typeof UserLearnLangReviewPreviewRoute
  '/admin/$lang/phrases/$id': typeof UserAdminLangPhrasesIdLazyRoute
  '/admin/$lang/requests/$id': typeof UserAdminLangRequestsIdLazyRoute
  '/friends/chats/$friendUid/recommend': typeof UserFriendsChatsFriendUidRecommendLazyRoute
  '/learn/$lang/requests/': typeof UserLearnLangRequestsIndexRoute
  '/learn/$lang/review/': typeof UserLearnLangReviewIndexRoute
  '/admin/$lang/phrases/': typeof UserAdminLangPhrasesIndexLazyRoute
  '/admin/$lang/requests/': typeof UserAdminLangRequestsIndexLazyRoute
  '/learn/$lang/playlists/': typeof UserLearnLangPlaylistsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsLazyRoute
  '/microcopy': typeof MicrocopyLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/request-removal': typeof RequestRemovalLazyRoute
  '/themes': typeof ThemesLazyRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/accept-invite': typeof UserAcceptInviteRoute
  '/getting-started': typeof UserGettingStartedRoute
  '/notifications': typeof UserNotificationsRoute
  '/welcome': typeof UserWelcomeRoute
  '/forgot-password': typeof AuthForgotPasswordLazyRoute
  '/set-new-password': typeof AuthSetNewPasswordLazyRoute
  '/chats/$lang': typeof ChatsLangLazyRoute
  '/chats': typeof ChatsIndexLazyRoute
  '/browse/charts': typeof UserBrowseChartsRoute
  '/friends/$uid': typeof UserFriendsUidRoute
  '/learn/add-deck': typeof UserLearnAddDeckRoute
  '/learn/contributions': typeof UserLearnContributionsRoute
  '/profile/change-email-confirm': typeof UserProfileChangeEmailConfirmRoute
  '/friends/invite': typeof UserFriendsInviteLazyRoute
  '/learn/archived': typeof UserLearnArchivedLazyRoute
  '/profile/change-email': typeof UserProfileChangeEmailLazyRoute
  '/profile/change-password': typeof UserProfileChangePasswordLazyRoute
  '/search/test': typeof UserSearchTestLazyRoute
  '/admin': typeof UserAdminIndexRoute
  '/browse': typeof UserBrowseIndexRoute
  '/friends': typeof UserFriendsIndexRoute
  '/learn': typeof UserLearnIndexRoute
  '/profile': typeof UserProfileIndexLazyRoute
  '/search': typeof UserSearchIndexLazyRoute
  '/friends/chats/$friendUid': typeof UserFriendsChatsFriendUidRouteWithChildren
  '/learn/$lang/bulk-add': typeof UserLearnLangBulkAddRoute
  '/learn/$lang/contributions': typeof UserLearnLangContributionsRoute
  '/learn/$lang/feed': typeof UserLearnLangFeedRoute
  '/learn/$lang/deck-settings': typeof UserLearnLangDeckSettingsLazyRoute
  '/learn/$lang/manage-deck': typeof UserLearnLangManageDeckLazyRoute
  '/learn/$lang/stats': typeof UserLearnLangStatsLazyRoute
  '/admin/$lang': typeof UserAdminLangIndexRoute
  '/learn/$lang': typeof UserLearnLangIndexRoute
  '/friends/chats': typeof UserFriendsChatsIndexLazyRoute
  '/learn/$lang/phrases/$id': typeof UserLearnLangPhrasesIdRoute
  '/learn/$lang/phrases/new': typeof UserLearnLangPhrasesNewRoute
  '/learn/$lang/playlists/$playlistId': typeof UserLearnLangPlaylistsPlaylistIdRoute
  '/learn/$lang/playlists/new': typeof UserLearnLangPlaylistsNewRoute
  '/learn/$lang/requests/$id': typeof UserLearnLangRequestsIdRoute
  '/learn/$lang/requests/new': typeof UserLearnLangRequestsNewRoute
  '/learn/$lang/review/go': typeof UserLearnLangReviewGoRoute
  '/learn/$lang/review/preview': typeof UserLearnLangReviewPreviewRoute
  '/admin/$lang/phrases/$id': typeof UserAdminLangPhrasesIdLazyRoute
  '/admin/$lang/requests/$id': typeof UserAdminLangRequestsIdLazyRoute
  '/friends/chats/$friendUid/recommend': typeof UserFriendsChatsFriendUidRecommendLazyRoute
  '/learn/$lang/requests': typeof UserLearnLangRequestsIndexRoute
  '/learn/$lang/review': typeof UserLearnLangReviewIndexRoute
  '/admin/$lang/phrases': typeof UserAdminLangPhrasesIndexLazyRoute
  '/admin/$lang/requests': typeof UserAdminLangRequestsIndexLazyRoute
  '/learn/$lang/playlists': typeof UserLearnLangPlaylistsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_user': typeof UserRouteWithChildren
  '/_auth': typeof AuthLazyRouteWithChildren
  '/chats': typeof ChatsLazyRouteWithChildren
  '/components': typeof ComponentsLazyRoute
  '/microcopy': typeof MicrocopyLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/request-removal': typeof RequestRemovalLazyRoute
  '/themes': typeof ThemesLazyRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_user/accept-invite': typeof UserAcceptInviteRoute
  '/_user/browse': typeof UserBrowseRouteWithChildren
  '/_user/friends': typeof UserFriendsRouteWithChildren
  '/_user/getting-started': typeof UserGettingStartedRoute
  '/_user/learn': typeof UserLearnRouteWithChildren
  '/_user/notifications': typeof UserNotificationsRoute
  '/_user/profile': typeof UserProfileRouteWithChildren
  '/_user/search': typeof UserSearchRouteWithChildren
  '/_user/welcome': typeof UserWelcomeRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordLazyRoute
  '/_auth/set-new-password': typeof AuthSetNewPasswordLazyRoute
  '/_user/admin': typeof UserAdminLazyRouteWithChildren
  '/chats/$lang': typeof ChatsLangLazyRoute
  '/chats/': typeof ChatsIndexLazyRoute
  '/_user/admin/$lang': typeof UserAdminLangRouteWithChildren
  '/_user/browse/charts': typeof UserBrowseChartsRoute
  '/_user/friends/$uid': typeof UserFriendsUidRoute
  '/_user/friends/chats': typeof UserFriendsChatsRouteWithChildren
  '/_user/learn/$lang': typeof UserLearnLangRouteWithChildren
  '/_user/learn/add-deck': typeof UserLearnAddDeckRoute
  '/_user/learn/contributions': typeof UserLearnContributionsRoute
  '/_user/profile/change-email-confirm': typeof UserProfileChangeEmailConfirmRoute
  '/_user/friends/invite': typeof UserFriendsInviteLazyRoute
  '/_user/learn/archived': typeof UserLearnArchivedLazyRoute
  '/_user/profile/change-email': typeof UserProfileChangeEmailLazyRoute
  '/_user/profile/change-password': typeof UserProfileChangePasswordLazyRoute
  '/_user/search/test': typeof UserSearchTestLazyRoute
  '/_user/admin/': typeof UserAdminIndexRoute
  '/_user/browse/': typeof UserBrowseIndexRoute
  '/_user/friends/': typeof UserFriendsIndexRoute
  '/_user/learn/': typeof UserLearnIndexRoute
  '/_user/profile/': typeof UserProfileIndexLazyRoute
  '/_user/search/': typeof UserSearchIndexLazyRoute
  '/_user/admin/$lang/phrases': typeof UserAdminLangPhrasesRouteWithChildren
  '/_user/admin/$lang/requests': typeof UserAdminLangRequestsRouteWithChildren
  '/_user/friends/chats/$friendUid': typeof UserFriendsChatsFriendUidRouteWithChildren
  '/_user/learn/$lang/bulk-add': typeof UserLearnLangBulkAddRoute
  '/_user/learn/$lang/contributions': typeof UserLearnLangContributionsRoute
  '/_user/learn/$lang/feed': typeof UserLearnLangFeedRoute
  '/_user/learn/$lang/playlists': typeof UserLearnLangPlaylistsRouteWithChildren
  '/_user/learn/$lang/review': typeof UserLearnLangReviewRouteWithChildren
  '/_user/learn/$lang/deck-settings': typeof UserLearnLangDeckSettingsLazyRoute
  '/_user/learn/$lang/manage-deck': typeof UserLearnLangManageDeckLazyRoute
  '/_user/learn/$lang/stats': typeof UserLearnLangStatsLazyRoute
  '/_user/admin/$lang/': typeof UserAdminLangIndexRoute
  '/_user/learn/$lang/': typeof UserLearnLangIndexRoute
  '/_user/friends/chats/': typeof UserFriendsChatsIndexLazyRoute
  '/_user/learn/$lang/phrases/$id': typeof UserLearnLangPhrasesIdRoute
  '/_user/learn/$lang/phrases/new': typeof UserLearnLangPhrasesNewRoute
  '/_user/learn/$lang/playlists/$playlistId': typeof UserLearnLangPlaylistsPlaylistIdRoute
  '/_user/learn/$lang/playlists/new': typeof UserLearnLangPlaylistsNewRoute
  '/_user/learn/$lang/requests/$id': typeof UserLearnLangRequestsIdRoute
  '/_user/learn/$lang/requests/new': typeof UserLearnLangRequestsNewRoute
  '/_user/learn/$lang/review/go': typeof UserLearnLangReviewGoRoute
  '/_user/learn/$lang/review/preview': typeof UserLearnLangReviewPreviewRoute
  '/_user/admin/$lang/phrases/$id': typeof UserAdminLangPhrasesIdLazyRoute
  '/_user/admin/$lang/requests/$id': typeof UserAdminLangRequestsIdLazyRoute
  '/_user/friends/chats/$friendUid/recommend': typeof UserFriendsChatsFriendUidRecommendLazyRoute
  '/_user/learn/$lang/requests/': typeof UserLearnLangRequestsIndexRoute
  '/_user/learn/$lang/review/': typeof UserLearnLangReviewIndexRoute
  '/_user/admin/$lang/phrases/': typeof UserAdminLangPhrasesIndexLazyRoute
  '/_user/admin/$lang/requests/': typeof UserAdminLangRequestsIndexLazyRoute
  '/_user/learn/$lang/playlists/': typeof UserLearnLangPlaylistsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chats'
    | '/components'
    | '/microcopy'
    | '/privacy-policy'
    | '/request-removal'
    | '/themes'
    | '/login'
    | '/signup'
    | '/accept-invite'
    | '/browse'
    | '/friends'
    | '/getting-started'
    | '/learn'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/welcome'
    | '/forgot-password'
    | '/set-new-password'
    | '/admin'
    | '/chats/$lang'
    | '/chats/'
    | '/admin/$lang'
    | '/browse/charts'
    | '/friends/$uid'
    | '/friends/chats'
    | '/learn/$lang'
    | '/learn/add-deck'
    | '/learn/contributions'
    | '/profile/change-email-confirm'
    | '/friends/invite'
    | '/learn/archived'
    | '/profile/change-email'
    | '/profile/change-password'
    | '/search/test'
    | '/admin/'
    | '/browse/'
    | '/friends/'
    | '/learn/'
    | '/profile/'
    | '/search/'
    | '/admin/$lang/phrases'
    | '/admin/$lang/requests'
    | '/friends/chats/$friendUid'
    | '/learn/$lang/bulk-add'
    | '/learn/$lang/contributions'
    | '/learn/$lang/feed'
    | '/learn/$lang/playlists'
    | '/learn/$lang/review'
    | '/learn/$lang/deck-settings'
    | '/learn/$lang/manage-deck'
    | '/learn/$lang/stats'
    | '/admin/$lang/'
    | '/learn/$lang/'
    | '/friends/chats/'
    | '/learn/$lang/phrases/$id'
    | '/learn/$lang/phrases/new'
    | '/learn/$lang/playlists/$playlistId'
    | '/learn/$lang/playlists/new'
    | '/learn/$lang/requests/$id'
    | '/learn/$lang/requests/new'
    | '/learn/$lang/review/go'
    | '/learn/$lang/review/preview'
    | '/admin/$lang/phrases/$id'
    | '/admin/$lang/requests/$id'
    | '/friends/chats/$friendUid/recommend'
    | '/learn/$lang/requests/'
    | '/learn/$lang/review/'
    | '/admin/$lang/phrases/'
    | '/admin/$lang/requests/'
    | '/learn/$lang/playlists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/microcopy'
    | '/privacy-policy'
    | '/request-removal'
    | '/themes'
    | '/login'
    | '/signup'
    | '/accept-invite'
    | '/getting-started'
    | '/notifications'
    | '/welcome'
    | '/forgot-password'
    | '/set-new-password'
    | '/chats/$lang'
    | '/chats'
    | '/browse/charts'
    | '/friends/$uid'
    | '/learn/add-deck'
    | '/learn/contributions'
    | '/profile/change-email-confirm'
    | '/friends/invite'
    | '/learn/archived'
    | '/profile/change-email'
    | '/profile/change-password'
    | '/search/test'
    | '/admin'
    | '/browse'
    | '/friends'
    | '/learn'
    | '/profile'
    | '/search'
    | '/friends/chats/$friendUid'
    | '/learn/$lang/bulk-add'
    | '/learn/$lang/contributions'
    | '/learn/$lang/feed'
    | '/learn/$lang/deck-settings'
    | '/learn/$lang/manage-deck'
    | '/learn/$lang/stats'
    | '/admin/$lang'
    | '/learn/$lang'
    | '/friends/chats'
    | '/learn/$lang/phrases/$id'
    | '/learn/$lang/phrases/new'
    | '/learn/$lang/playlists/$playlistId'
    | '/learn/$lang/playlists/new'
    | '/learn/$lang/requests/$id'
    | '/learn/$lang/requests/new'
    | '/learn/$lang/review/go'
    | '/learn/$lang/review/preview'
    | '/admin/$lang/phrases/$id'
    | '/admin/$lang/requests/$id'
    | '/friends/chats/$friendUid/recommend'
    | '/learn/$lang/requests'
    | '/learn/$lang/review'
    | '/admin/$lang/phrases'
    | '/admin/$lang/requests'
    | '/learn/$lang/playlists'
  id:
    | '__root__'
    | '/'
    | '/_user'
    | '/_auth'
    | '/chats'
    | '/components'
    | '/microcopy'
    | '/privacy-policy'
    | '/request-removal'
    | '/themes'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_user/accept-invite'
    | '/_user/browse'
    | '/_user/friends'
    | '/_user/getting-started'
    | '/_user/learn'
    | '/_user/notifications'
    | '/_user/profile'
    | '/_user/search'
    | '/_user/welcome'
    | '/_auth/forgot-password'
    | '/_auth/set-new-password'
    | '/_user/admin'
    | '/chats/$lang'
    | '/chats/'
    | '/_user/admin/$lang'
    | '/_user/browse/charts'
    | '/_user/friends/$uid'
    | '/_user/friends/chats'
    | '/_user/learn/$lang'
    | '/_user/learn/add-deck'
    | '/_user/learn/contributions'
    | '/_user/profile/change-email-confirm'
    | '/_user/friends/invite'
    | '/_user/learn/archived'
    | '/_user/profile/change-email'
    | '/_user/profile/change-password'
    | '/_user/search/test'
    | '/_user/admin/'
    | '/_user/browse/'
    | '/_user/friends/'
    | '/_user/learn/'
    | '/_user/profile/'
    | '/_user/search/'
    | '/_user/admin/$lang/phrases'
    | '/_user/admin/$lang/requests'
    | '/_user/friends/chats/$friendUid'
    | '/_user/learn/$lang/bulk-add'
    | '/_user/learn/$lang/contributions'
    | '/_user/learn/$lang/feed'
    | '/_user/learn/$lang/playlists'
    | '/_user/learn/$lang/review'
    | '/_user/learn/$lang/deck-settings'
    | '/_user/learn/$lang/manage-deck'
    | '/_user/learn/$lang/stats'
    | '/_user/admin/$lang/'
    | '/_user/learn/$lang/'
    | '/_user/friends/chats/'
    | '/_user/learn/$lang/phrases/$id'
    | '/_user/learn/$lang/phrases/new'
    | '/_user/learn/$lang/playlists/$playlistId'
    | '/_user/learn/$lang/playlists/new'
    | '/_user/learn/$lang/requests/$id'
    | '/_user/learn/$lang/requests/new'
    | '/_user/learn/$lang/review/go'
    | '/_user/learn/$lang/review/preview'
    | '/_user/admin/$lang/phrases/$id'
    | '/_user/admin/$lang/requests/$id'
    | '/_user/friends/chats/$friendUid/recommend'
    | '/_user/learn/$lang/requests/'
    | '/_user/learn/$lang/review/'
    | '/_user/admin/$lang/phrases/'
    | '/_user/admin/$lang/requests/'
    | '/_user/learn/$lang/playlists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRoute: typeof UserRouteWithChildren
  AuthLazyRoute: typeof AuthLazyRouteWithChildren
  ChatsLazyRoute: typeof ChatsLazyRouteWithChildren
  ComponentsLazyRoute: typeof ComponentsLazyRoute
  MicrocopyLazyRoute: typeof MicrocopyLazyRoute
  PrivacyPolicyLazyRoute: typeof PrivacyPolicyLazyRoute
  RequestRemovalLazyRoute: typeof RequestRemovalLazyRoute
  ThemesLazyRoute: typeof ThemesLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-removal': {
      id: '/request-removal'
      path: '/request-removal'
      fullPath: '/request-removal'
      preLoaderRoute: typeof RequestRemovalLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microcopy': {
      id: '/microcopy'
      path: '/microcopy'
      fullPath: '/microcopy'
      preLoaderRoute: typeof MicrocopyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexLazyRouteImport
      parentRoute: typeof ChatsLazyRoute
    }
    '/chats/$lang': {
      id: '/chats/$lang'
      path: '/$lang'
      fullPath: '/chats/$lang'
      preLoaderRoute: typeof ChatsLangLazyRouteImport
      parentRoute: typeof ChatsLazyRoute
    }
    '/_user/admin': {
      id: '/_user/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof UserAdminLazyRouteImport
      parentRoute: typeof UserRoute
    }
    '/_auth/set-new-password': {
      id: '/_auth/set-new-password'
      path: '/set-new-password'
      fullPath: '/set-new-password'
      preLoaderRoute: typeof AuthSetNewPasswordLazyRouteImport
      parentRoute: typeof AuthLazyRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordLazyRouteImport
      parentRoute: typeof AuthLazyRoute
    }
    '/_user/welcome': {
      id: '/_user/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof UserWelcomeRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/search': {
      id: '/_user/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof UserSearchRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/profile': {
      id: '/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/notifications': {
      id: '/_user/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof UserNotificationsRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/learn': {
      id: '/_user/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof UserLearnRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/getting-started': {
      id: '/_user/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof UserGettingStartedRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/friends': {
      id: '/_user/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof UserFriendsRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/browse': {
      id: '/_user/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof UserBrowseRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/accept-invite': {
      id: '/_user/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof UserAcceptInviteRouteImport
      parentRoute: typeof UserRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthLazyRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthLazyRoute
    }
    '/_user/search/': {
      id: '/_user/search/'
      path: '/'
      fullPath: '/search/'
      preLoaderRoute: typeof UserSearchIndexLazyRouteImport
      parentRoute: typeof UserSearchRoute
    }
    '/_user/profile/': {
      id: '/_user/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof UserProfileIndexLazyRouteImport
      parentRoute: typeof UserProfileRoute
    }
    '/_user/learn/': {
      id: '/_user/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof UserLearnIndexRouteImport
      parentRoute: typeof UserLearnRoute
    }
    '/_user/friends/': {
      id: '/_user/friends/'
      path: '/'
      fullPath: '/friends/'
      preLoaderRoute: typeof UserFriendsIndexRouteImport
      parentRoute: typeof UserFriendsRoute
    }
    '/_user/browse/': {
      id: '/_user/browse/'
      path: '/'
      fullPath: '/browse/'
      preLoaderRoute: typeof UserBrowseIndexRouteImport
      parentRoute: typeof UserBrowseRoute
    }
    '/_user/admin/': {
      id: '/_user/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof UserAdminIndexRouteImport
      parentRoute: typeof UserAdminLazyRoute
    }
    '/_user/search/test': {
      id: '/_user/search/test'
      path: '/test'
      fullPath: '/search/test'
      preLoaderRoute: typeof UserSearchTestLazyRouteImport
      parentRoute: typeof UserSearchRoute
    }
    '/_user/profile/change-password': {
      id: '/_user/profile/change-password'
      path: '/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof UserProfileChangePasswordLazyRouteImport
      parentRoute: typeof UserProfileRoute
    }
    '/_user/profile/change-email': {
      id: '/_user/profile/change-email'
      path: '/change-email'
      fullPath: '/profile/change-email'
      preLoaderRoute: typeof UserProfileChangeEmailLazyRouteImport
      parentRoute: typeof UserProfileRoute
    }
    '/_user/learn/archived': {
      id: '/_user/learn/archived'
      path: '/archived'
      fullPath: '/learn/archived'
      preLoaderRoute: typeof UserLearnArchivedLazyRouteImport
      parentRoute: typeof UserLearnRoute
    }
    '/_user/friends/invite': {
      id: '/_user/friends/invite'
      path: '/invite'
      fullPath: '/friends/invite'
      preLoaderRoute: typeof UserFriendsInviteLazyRouteImport
      parentRoute: typeof UserFriendsRoute
    }
    '/_user/profile/change-email-confirm': {
      id: '/_user/profile/change-email-confirm'
      path: '/change-email-confirm'
      fullPath: '/profile/change-email-confirm'
      preLoaderRoute: typeof UserProfileChangeEmailConfirmRouteImport
      parentRoute: typeof UserProfileRoute
    }
    '/_user/learn/contributions': {
      id: '/_user/learn/contributions'
      path: '/contributions'
      fullPath: '/learn/contributions'
      preLoaderRoute: typeof UserLearnContributionsRouteImport
      parentRoute: typeof UserLearnRoute
    }
    '/_user/learn/add-deck': {
      id: '/_user/learn/add-deck'
      path: '/add-deck'
      fullPath: '/learn/add-deck'
      preLoaderRoute: typeof UserLearnAddDeckRouteImport
      parentRoute: typeof UserLearnRoute
    }
    '/_user/learn/$lang': {
      id: '/_user/learn/$lang'
      path: '/$lang'
      fullPath: '/learn/$lang'
      preLoaderRoute: typeof UserLearnLangRouteImport
      parentRoute: typeof UserLearnRoute
    }
    '/_user/friends/chats': {
      id: '/_user/friends/chats'
      path: '/chats'
      fullPath: '/friends/chats'
      preLoaderRoute: typeof UserFriendsChatsRouteImport
      parentRoute: typeof UserFriendsRoute
    }
    '/_user/friends/$uid': {
      id: '/_user/friends/$uid'
      path: '/$uid'
      fullPath: '/friends/$uid'
      preLoaderRoute: typeof UserFriendsUidRouteImport
      parentRoute: typeof UserFriendsRoute
    }
    '/_user/browse/charts': {
      id: '/_user/browse/charts'
      path: '/charts'
      fullPath: '/browse/charts'
      preLoaderRoute: typeof UserBrowseChartsRouteImport
      parentRoute: typeof UserBrowseRoute
    }
    '/_user/admin/$lang': {
      id: '/_user/admin/$lang'
      path: '/$lang'
      fullPath: '/admin/$lang'
      preLoaderRoute: typeof UserAdminLangRouteImport
      parentRoute: typeof UserAdminLazyRoute
    }
    '/_user/friends/chats/': {
      id: '/_user/friends/chats/'
      path: '/'
      fullPath: '/friends/chats/'
      preLoaderRoute: typeof UserFriendsChatsIndexLazyRouteImport
      parentRoute: typeof UserFriendsChatsRoute
    }
    '/_user/learn/$lang/': {
      id: '/_user/learn/$lang/'
      path: '/'
      fullPath: '/learn/$lang/'
      preLoaderRoute: typeof UserLearnLangIndexRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/admin/$lang/': {
      id: '/_user/admin/$lang/'
      path: '/'
      fullPath: '/admin/$lang/'
      preLoaderRoute: typeof UserAdminLangIndexRouteImport
      parentRoute: typeof UserAdminLangRoute
    }
    '/_user/learn/$lang/stats': {
      id: '/_user/learn/$lang/stats'
      path: '/stats'
      fullPath: '/learn/$lang/stats'
      preLoaderRoute: typeof UserLearnLangStatsLazyRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/manage-deck': {
      id: '/_user/learn/$lang/manage-deck'
      path: '/manage-deck'
      fullPath: '/learn/$lang/manage-deck'
      preLoaderRoute: typeof UserLearnLangManageDeckLazyRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/deck-settings': {
      id: '/_user/learn/$lang/deck-settings'
      path: '/deck-settings'
      fullPath: '/learn/$lang/deck-settings'
      preLoaderRoute: typeof UserLearnLangDeckSettingsLazyRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/review': {
      id: '/_user/learn/$lang/review'
      path: '/review'
      fullPath: '/learn/$lang/review'
      preLoaderRoute: typeof UserLearnLangReviewRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/playlists': {
      id: '/_user/learn/$lang/playlists'
      path: '/playlists'
      fullPath: '/learn/$lang/playlists'
      preLoaderRoute: typeof UserLearnLangPlaylistsRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/feed': {
      id: '/_user/learn/$lang/feed'
      path: '/feed'
      fullPath: '/learn/$lang/feed'
      preLoaderRoute: typeof UserLearnLangFeedRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/contributions': {
      id: '/_user/learn/$lang/contributions'
      path: '/contributions'
      fullPath: '/learn/$lang/contributions'
      preLoaderRoute: typeof UserLearnLangContributionsRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/bulk-add': {
      id: '/_user/learn/$lang/bulk-add'
      path: '/bulk-add'
      fullPath: '/learn/$lang/bulk-add'
      preLoaderRoute: typeof UserLearnLangBulkAddRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/friends/chats/$friendUid': {
      id: '/_user/friends/chats/$friendUid'
      path: '/$friendUid'
      fullPath: '/friends/chats/$friendUid'
      preLoaderRoute: typeof UserFriendsChatsFriendUidRouteImport
      parentRoute: typeof UserFriendsChatsRoute
    }
    '/_user/admin/$lang/requests': {
      id: '/_user/admin/$lang/requests'
      path: '/requests'
      fullPath: '/admin/$lang/requests'
      preLoaderRoute: typeof UserAdminLangRequestsRouteImport
      parentRoute: typeof UserAdminLangRoute
    }
    '/_user/admin/$lang/phrases': {
      id: '/_user/admin/$lang/phrases'
      path: '/phrases'
      fullPath: '/admin/$lang/phrases'
      preLoaderRoute: typeof UserAdminLangPhrasesRouteImport
      parentRoute: typeof UserAdminLangRoute
    }
    '/_user/learn/$lang/playlists/': {
      id: '/_user/learn/$lang/playlists/'
      path: '/'
      fullPath: '/learn/$lang/playlists/'
      preLoaderRoute: typeof UserLearnLangPlaylistsIndexLazyRouteImport
      parentRoute: typeof UserLearnLangPlaylistsRoute
    }
    '/_user/admin/$lang/requests/': {
      id: '/_user/admin/$lang/requests/'
      path: '/'
      fullPath: '/admin/$lang/requests/'
      preLoaderRoute: typeof UserAdminLangRequestsIndexLazyRouteImport
      parentRoute: typeof UserAdminLangRequestsRoute
    }
    '/_user/admin/$lang/phrases/': {
      id: '/_user/admin/$lang/phrases/'
      path: '/'
      fullPath: '/admin/$lang/phrases/'
      preLoaderRoute: typeof UserAdminLangPhrasesIndexLazyRouteImport
      parentRoute: typeof UserAdminLangPhrasesRoute
    }
    '/_user/learn/$lang/review/': {
      id: '/_user/learn/$lang/review/'
      path: '/'
      fullPath: '/learn/$lang/review/'
      preLoaderRoute: typeof UserLearnLangReviewIndexRouteImport
      parentRoute: typeof UserLearnLangReviewRoute
    }
    '/_user/learn/$lang/requests/': {
      id: '/_user/learn/$lang/requests/'
      path: '/requests'
      fullPath: '/learn/$lang/requests/'
      preLoaderRoute: typeof UserLearnLangRequestsIndexRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/friends/chats/$friendUid/recommend': {
      id: '/_user/friends/chats/$friendUid/recommend'
      path: '/recommend'
      fullPath: '/friends/chats/$friendUid/recommend'
      preLoaderRoute: typeof UserFriendsChatsFriendUidRecommendLazyRouteImport
      parentRoute: typeof UserFriendsChatsFriendUidRoute
    }
    '/_user/admin/$lang/requests/$id': {
      id: '/_user/admin/$lang/requests/$id'
      path: '/$id'
      fullPath: '/admin/$lang/requests/$id'
      preLoaderRoute: typeof UserAdminLangRequestsIdLazyRouteImport
      parentRoute: typeof UserAdminLangRequestsRoute
    }
    '/_user/admin/$lang/phrases/$id': {
      id: '/_user/admin/$lang/phrases/$id'
      path: '/$id'
      fullPath: '/admin/$lang/phrases/$id'
      preLoaderRoute: typeof UserAdminLangPhrasesIdLazyRouteImport
      parentRoute: typeof UserAdminLangPhrasesRoute
    }
    '/_user/learn/$lang/review/preview': {
      id: '/_user/learn/$lang/review/preview'
      path: '/preview'
      fullPath: '/learn/$lang/review/preview'
      preLoaderRoute: typeof UserLearnLangReviewPreviewRouteImport
      parentRoute: typeof UserLearnLangReviewRoute
    }
    '/_user/learn/$lang/review/go': {
      id: '/_user/learn/$lang/review/go'
      path: '/go'
      fullPath: '/learn/$lang/review/go'
      preLoaderRoute: typeof UserLearnLangReviewGoRouteImport
      parentRoute: typeof UserLearnLangReviewRoute
    }
    '/_user/learn/$lang/requests/new': {
      id: '/_user/learn/$lang/requests/new'
      path: '/requests/new'
      fullPath: '/learn/$lang/requests/new'
      preLoaderRoute: typeof UserLearnLangRequestsNewRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/requests/$id': {
      id: '/_user/learn/$lang/requests/$id'
      path: '/requests/$id'
      fullPath: '/learn/$lang/requests/$id'
      preLoaderRoute: typeof UserLearnLangRequestsIdRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/playlists/new': {
      id: '/_user/learn/$lang/playlists/new'
      path: '/new'
      fullPath: '/learn/$lang/playlists/new'
      preLoaderRoute: typeof UserLearnLangPlaylistsNewRouteImport
      parentRoute: typeof UserLearnLangPlaylistsRoute
    }
    '/_user/learn/$lang/playlists/$playlistId': {
      id: '/_user/learn/$lang/playlists/$playlistId'
      path: '/$playlistId'
      fullPath: '/learn/$lang/playlists/$playlistId'
      preLoaderRoute: typeof UserLearnLangPlaylistsPlaylistIdRouteImport
      parentRoute: typeof UserLearnLangPlaylistsRoute
    }
    '/_user/learn/$lang/phrases/new': {
      id: '/_user/learn/$lang/phrases/new'
      path: '/phrases/new'
      fullPath: '/learn/$lang/phrases/new'
      preLoaderRoute: typeof UserLearnLangPhrasesNewRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
    '/_user/learn/$lang/phrases/$id': {
      id: '/_user/learn/$lang/phrases/$id'
      path: '/phrases/$id'
      fullPath: '/learn/$lang/phrases/$id'
      preLoaderRoute: typeof UserLearnLangPhrasesIdRouteImport
      parentRoute: typeof UserLearnLangRoute
    }
  }
}

interface UserBrowseRouteChildren {
  UserBrowseChartsRoute: typeof UserBrowseChartsRoute
  UserBrowseIndexRoute: typeof UserBrowseIndexRoute
}

const UserBrowseRouteChildren: UserBrowseRouteChildren = {
  UserBrowseChartsRoute: UserBrowseChartsRoute,
  UserBrowseIndexRoute: UserBrowseIndexRoute,
}

const UserBrowseRouteWithChildren = UserBrowseRoute._addFileChildren(
  UserBrowseRouteChildren,
)

interface UserFriendsChatsFriendUidRouteChildren {
  UserFriendsChatsFriendUidRecommendLazyRoute: typeof UserFriendsChatsFriendUidRecommendLazyRoute
}

const UserFriendsChatsFriendUidRouteChildren: UserFriendsChatsFriendUidRouteChildren =
  {
    UserFriendsChatsFriendUidRecommendLazyRoute:
      UserFriendsChatsFriendUidRecommendLazyRoute,
  }

const UserFriendsChatsFriendUidRouteWithChildren =
  UserFriendsChatsFriendUidRoute._addFileChildren(
    UserFriendsChatsFriendUidRouteChildren,
  )

interface UserFriendsChatsRouteChildren {
  UserFriendsChatsFriendUidRoute: typeof UserFriendsChatsFriendUidRouteWithChildren
  UserFriendsChatsIndexLazyRoute: typeof UserFriendsChatsIndexLazyRoute
}

const UserFriendsChatsRouteChildren: UserFriendsChatsRouteChildren = {
  UserFriendsChatsFriendUidRoute: UserFriendsChatsFriendUidRouteWithChildren,
  UserFriendsChatsIndexLazyRoute: UserFriendsChatsIndexLazyRoute,
}

const UserFriendsChatsRouteWithChildren =
  UserFriendsChatsRoute._addFileChildren(UserFriendsChatsRouteChildren)

interface UserFriendsRouteChildren {
  UserFriendsUidRoute: typeof UserFriendsUidRoute
  UserFriendsChatsRoute: typeof UserFriendsChatsRouteWithChildren
  UserFriendsInviteLazyRoute: typeof UserFriendsInviteLazyRoute
  UserFriendsIndexRoute: typeof UserFriendsIndexRoute
}

const UserFriendsRouteChildren: UserFriendsRouteChildren = {
  UserFriendsUidRoute: UserFriendsUidRoute,
  UserFriendsChatsRoute: UserFriendsChatsRouteWithChildren,
  UserFriendsInviteLazyRoute: UserFriendsInviteLazyRoute,
  UserFriendsIndexRoute: UserFriendsIndexRoute,
}

const UserFriendsRouteWithChildren = UserFriendsRoute._addFileChildren(
  UserFriendsRouteChildren,
)

interface UserLearnLangPlaylistsRouteChildren {
  UserLearnLangPlaylistsPlaylistIdRoute: typeof UserLearnLangPlaylistsPlaylistIdRoute
  UserLearnLangPlaylistsNewRoute: typeof UserLearnLangPlaylistsNewRoute
  UserLearnLangPlaylistsIndexLazyRoute: typeof UserLearnLangPlaylistsIndexLazyRoute
}

const UserLearnLangPlaylistsRouteChildren: UserLearnLangPlaylistsRouteChildren =
  {
    UserLearnLangPlaylistsPlaylistIdRoute:
      UserLearnLangPlaylistsPlaylistIdRoute,
    UserLearnLangPlaylistsNewRoute: UserLearnLangPlaylistsNewRoute,
    UserLearnLangPlaylistsIndexLazyRoute: UserLearnLangPlaylistsIndexLazyRoute,
  }

const UserLearnLangPlaylistsRouteWithChildren =
  UserLearnLangPlaylistsRoute._addFileChildren(
    UserLearnLangPlaylistsRouteChildren,
  )

interface UserLearnLangReviewRouteChildren {
  UserLearnLangReviewGoRoute: typeof UserLearnLangReviewGoRoute
  UserLearnLangReviewPreviewRoute: typeof UserLearnLangReviewPreviewRoute
  UserLearnLangReviewIndexRoute: typeof UserLearnLangReviewIndexRoute
}

const UserLearnLangReviewRouteChildren: UserLearnLangReviewRouteChildren = {
  UserLearnLangReviewGoRoute: UserLearnLangReviewGoRoute,
  UserLearnLangReviewPreviewRoute: UserLearnLangReviewPreviewRoute,
  UserLearnLangReviewIndexRoute: UserLearnLangReviewIndexRoute,
}

const UserLearnLangReviewRouteWithChildren =
  UserLearnLangReviewRoute._addFileChildren(UserLearnLangReviewRouteChildren)

interface UserLearnLangRouteChildren {
  UserLearnLangBulkAddRoute: typeof UserLearnLangBulkAddRoute
  UserLearnLangContributionsRoute: typeof UserLearnLangContributionsRoute
  UserLearnLangFeedRoute: typeof UserLearnLangFeedRoute
  UserLearnLangPlaylistsRoute: typeof UserLearnLangPlaylistsRouteWithChildren
  UserLearnLangReviewRoute: typeof UserLearnLangReviewRouteWithChildren
  UserLearnLangDeckSettingsLazyRoute: typeof UserLearnLangDeckSettingsLazyRoute
  UserLearnLangManageDeckLazyRoute: typeof UserLearnLangManageDeckLazyRoute
  UserLearnLangStatsLazyRoute: typeof UserLearnLangStatsLazyRoute
  UserLearnLangIndexRoute: typeof UserLearnLangIndexRoute
  UserLearnLangPhrasesIdRoute: typeof UserLearnLangPhrasesIdRoute
  UserLearnLangPhrasesNewRoute: typeof UserLearnLangPhrasesNewRoute
  UserLearnLangRequestsIdRoute: typeof UserLearnLangRequestsIdRoute
  UserLearnLangRequestsNewRoute: typeof UserLearnLangRequestsNewRoute
  UserLearnLangRequestsIndexRoute: typeof UserLearnLangRequestsIndexRoute
}

const UserLearnLangRouteChildren: UserLearnLangRouteChildren = {
  UserLearnLangBulkAddRoute: UserLearnLangBulkAddRoute,
  UserLearnLangContributionsRoute: UserLearnLangContributionsRoute,
  UserLearnLangFeedRoute: UserLearnLangFeedRoute,
  UserLearnLangPlaylistsRoute: UserLearnLangPlaylistsRouteWithChildren,
  UserLearnLangReviewRoute: UserLearnLangReviewRouteWithChildren,
  UserLearnLangDeckSettingsLazyRoute: UserLearnLangDeckSettingsLazyRoute,
  UserLearnLangManageDeckLazyRoute: UserLearnLangManageDeckLazyRoute,
  UserLearnLangStatsLazyRoute: UserLearnLangStatsLazyRoute,
  UserLearnLangIndexRoute: UserLearnLangIndexRoute,
  UserLearnLangPhrasesIdRoute: UserLearnLangPhrasesIdRoute,
  UserLearnLangPhrasesNewRoute: UserLearnLangPhrasesNewRoute,
  UserLearnLangRequestsIdRoute: UserLearnLangRequestsIdRoute,
  UserLearnLangRequestsNewRoute: UserLearnLangRequestsNewRoute,
  UserLearnLangRequestsIndexRoute: UserLearnLangRequestsIndexRoute,
}

const UserLearnLangRouteWithChildren = UserLearnLangRoute._addFileChildren(
  UserLearnLangRouteChildren,
)

interface UserLearnRouteChildren {
  UserLearnLangRoute: typeof UserLearnLangRouteWithChildren
  UserLearnAddDeckRoute: typeof UserLearnAddDeckRoute
  UserLearnContributionsRoute: typeof UserLearnContributionsRoute
  UserLearnArchivedLazyRoute: typeof UserLearnArchivedLazyRoute
  UserLearnIndexRoute: typeof UserLearnIndexRoute
}

const UserLearnRouteChildren: UserLearnRouteChildren = {
  UserLearnLangRoute: UserLearnLangRouteWithChildren,
  UserLearnAddDeckRoute: UserLearnAddDeckRoute,
  UserLearnContributionsRoute: UserLearnContributionsRoute,
  UserLearnArchivedLazyRoute: UserLearnArchivedLazyRoute,
  UserLearnIndexRoute: UserLearnIndexRoute,
}

const UserLearnRouteWithChildren = UserLearnRoute._addFileChildren(
  UserLearnRouteChildren,
)

interface UserProfileRouteChildren {
  UserProfileChangeEmailConfirmRoute: typeof UserProfileChangeEmailConfirmRoute
  UserProfileChangeEmailLazyRoute: typeof UserProfileChangeEmailLazyRoute
  UserProfileChangePasswordLazyRoute: typeof UserProfileChangePasswordLazyRoute
  UserProfileIndexLazyRoute: typeof UserProfileIndexLazyRoute
}

const UserProfileRouteChildren: UserProfileRouteChildren = {
  UserProfileChangeEmailConfirmRoute: UserProfileChangeEmailConfirmRoute,
  UserProfileChangeEmailLazyRoute: UserProfileChangeEmailLazyRoute,
  UserProfileChangePasswordLazyRoute: UserProfileChangePasswordLazyRoute,
  UserProfileIndexLazyRoute: UserProfileIndexLazyRoute,
}

const UserProfileRouteWithChildren = UserProfileRoute._addFileChildren(
  UserProfileRouteChildren,
)

interface UserSearchRouteChildren {
  UserSearchTestLazyRoute: typeof UserSearchTestLazyRoute
  UserSearchIndexLazyRoute: typeof UserSearchIndexLazyRoute
}

const UserSearchRouteChildren: UserSearchRouteChildren = {
  UserSearchTestLazyRoute: UserSearchTestLazyRoute,
  UserSearchIndexLazyRoute: UserSearchIndexLazyRoute,
}

const UserSearchRouteWithChildren = UserSearchRoute._addFileChildren(
  UserSearchRouteChildren,
)

interface UserAdminLangPhrasesRouteChildren {
  UserAdminLangPhrasesIdLazyRoute: typeof UserAdminLangPhrasesIdLazyRoute
  UserAdminLangPhrasesIndexLazyRoute: typeof UserAdminLangPhrasesIndexLazyRoute
}

const UserAdminLangPhrasesRouteChildren: UserAdminLangPhrasesRouteChildren = {
  UserAdminLangPhrasesIdLazyRoute: UserAdminLangPhrasesIdLazyRoute,
  UserAdminLangPhrasesIndexLazyRoute: UserAdminLangPhrasesIndexLazyRoute,
}

const UserAdminLangPhrasesRouteWithChildren =
  UserAdminLangPhrasesRoute._addFileChildren(UserAdminLangPhrasesRouteChildren)

interface UserAdminLangRequestsRouteChildren {
  UserAdminLangRequestsIdLazyRoute: typeof UserAdminLangRequestsIdLazyRoute
  UserAdminLangRequestsIndexLazyRoute: typeof UserAdminLangRequestsIndexLazyRoute
}

const UserAdminLangRequestsRouteChildren: UserAdminLangRequestsRouteChildren = {
  UserAdminLangRequestsIdLazyRoute: UserAdminLangRequestsIdLazyRoute,
  UserAdminLangRequestsIndexLazyRoute: UserAdminLangRequestsIndexLazyRoute,
}

const UserAdminLangRequestsRouteWithChildren =
  UserAdminLangRequestsRoute._addFileChildren(
    UserAdminLangRequestsRouteChildren,
  )

interface UserAdminLangRouteChildren {
  UserAdminLangPhrasesRoute: typeof UserAdminLangPhrasesRouteWithChildren
  UserAdminLangRequestsRoute: typeof UserAdminLangRequestsRouteWithChildren
  UserAdminLangIndexRoute: typeof UserAdminLangIndexRoute
}

const UserAdminLangRouteChildren: UserAdminLangRouteChildren = {
  UserAdminLangPhrasesRoute: UserAdminLangPhrasesRouteWithChildren,
  UserAdminLangRequestsRoute: UserAdminLangRequestsRouteWithChildren,
  UserAdminLangIndexRoute: UserAdminLangIndexRoute,
}

const UserAdminLangRouteWithChildren = UserAdminLangRoute._addFileChildren(
  UserAdminLangRouteChildren,
)

interface UserAdminLazyRouteChildren {
  UserAdminLangRoute: typeof UserAdminLangRouteWithChildren
  UserAdminIndexRoute: typeof UserAdminIndexRoute
}

const UserAdminLazyRouteChildren: UserAdminLazyRouteChildren = {
  UserAdminLangRoute: UserAdminLangRouteWithChildren,
  UserAdminIndexRoute: UserAdminIndexRoute,
}

const UserAdminLazyRouteWithChildren = UserAdminLazyRoute._addFileChildren(
  UserAdminLazyRouteChildren,
)

interface UserRouteChildren {
  UserAcceptInviteRoute: typeof UserAcceptInviteRoute
  UserBrowseRoute: typeof UserBrowseRouteWithChildren
  UserFriendsRoute: typeof UserFriendsRouteWithChildren
  UserGettingStartedRoute: typeof UserGettingStartedRoute
  UserLearnRoute: typeof UserLearnRouteWithChildren
  UserNotificationsRoute: typeof UserNotificationsRoute
  UserProfileRoute: typeof UserProfileRouteWithChildren
  UserSearchRoute: typeof UserSearchRouteWithChildren
  UserWelcomeRoute: typeof UserWelcomeRoute
  UserAdminLazyRoute: typeof UserAdminLazyRouteWithChildren
}

const UserRouteChildren: UserRouteChildren = {
  UserAcceptInviteRoute: UserAcceptInviteRoute,
  UserBrowseRoute: UserBrowseRouteWithChildren,
  UserFriendsRoute: UserFriendsRouteWithChildren,
  UserGettingStartedRoute: UserGettingStartedRoute,
  UserLearnRoute: UserLearnRouteWithChildren,
  UserNotificationsRoute: UserNotificationsRoute,
  UserProfileRoute: UserProfileRouteWithChildren,
  UserSearchRoute: UserSearchRouteWithChildren,
  UserWelcomeRoute: UserWelcomeRoute,
  UserAdminLazyRoute: UserAdminLazyRouteWithChildren,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

interface AuthLazyRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthForgotPasswordLazyRoute: typeof AuthForgotPasswordLazyRoute
  AuthSetNewPasswordLazyRoute: typeof AuthSetNewPasswordLazyRoute
}

const AuthLazyRouteChildren: AuthLazyRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthForgotPasswordLazyRoute: AuthForgotPasswordLazyRoute,
  AuthSetNewPasswordLazyRoute: AuthSetNewPasswordLazyRoute,
}

const AuthLazyRouteWithChildren = AuthLazyRoute._addFileChildren(
  AuthLazyRouteChildren,
)

interface ChatsLazyRouteChildren {
  ChatsLangLazyRoute: typeof ChatsLangLazyRoute
  ChatsIndexLazyRoute: typeof ChatsIndexLazyRoute
}

const ChatsLazyRouteChildren: ChatsLazyRouteChildren = {
  ChatsLangLazyRoute: ChatsLangLazyRoute,
  ChatsIndexLazyRoute: ChatsIndexLazyRoute,
}

const ChatsLazyRouteWithChildren = ChatsLazyRoute._addFileChildren(
  ChatsLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRoute: UserRouteWithChildren,
  AuthLazyRoute: AuthLazyRouteWithChildren,
  ChatsLazyRoute: ChatsLazyRouteWithChildren,
  ComponentsLazyRoute: ComponentsLazyRoute,
  MicrocopyLazyRoute: MicrocopyLazyRoute,
  PrivacyPolicyLazyRoute: PrivacyPolicyLazyRoute,
  RequestRemovalLazyRoute: RequestRemovalLazyRoute,
  ThemesLazyRoute: ThemesLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
