-- Phase 1: Embedding Infrastructure
-- Adds pgvector, embedding storage, config tracking, queue, and triggers
-- for automatic embedding generation when phrase data changes.
-- Enable pgvector extension for vector similarity search
create extension if not exists vector
with
	schema extensions;

-- ============================================================================
-- embedding_config: track which model produced embeddings (safe model swaps)
-- ============================================================================
create table public.embedding_config (
	id uuid default gen_random_uuid() primary key,
	model_name text not null,
	model_provider text not null,
	dimensions int not null,
	is_active boolean default true not null,
	created_at timestamptz default now() not null
);

alter table public.embedding_config owner to postgres;

-- Only one active config at a time
create unique index idx_embedding_config_active on embedding_config (is_active)
where
	is_active = true;

comment on table public.embedding_config is 'Tracks which embedding model produced vectors. Allows safe model swaps by creating a new config row.';

-- Seed initial config (model is a runtime choice — change this row to swap models)
insert into
	embedding_config (model_name, model_provider, dimensions, is_active)
values
	('qwen/qwen3-embedding-8b', 'openrouter', 1024, true);

-- ============================================================================
-- phrase_embedding: stores vector embeddings for each phrase
-- Separate table (not a column on phrase) so we can:
--   - Re-embed all phrases when changing models
--   - Have multiple embedding versions side by side
--   - Keep the phrase table clean
-- ============================================================================
create table public.phrase_embedding (
	phrase_id uuid not null references phrase (id) on delete cascade,
	config_id uuid not null references embedding_config (id),
	embedding extensions.vector (1024) not null,
	embedding_text text not null,
	created_at timestamptz default now() not null,
	primary key (phrase_id, config_id)
);

alter table public.phrase_embedding owner to postgres;

comment on table public.phrase_embedding is 'Vector embeddings for phrases, generated by the active embedding model. embedding_text stores the exact text that was embedded for cache validation.';

comment on column public.phrase_embedding.embedding_text is 'The exact text that was embedded — used for cache validation to skip re-embedding unchanged phrases.';

-- HNSW index for fast approximate nearest neighbor search
create index idx_phrase_embedding_hnsw on phrase_embedding using hnsw (embedding extensions.vector_cosine_ops)
with
	(m = 16, ef_construction = 64);

-- Index for looking up embeddings by phrase
create index idx_phrase_embedding_phrase on phrase_embedding (phrase_id);

-- ============================================================================
-- phrase_embedding_queue: phrases needing (re-)embedding
-- ============================================================================
create table public.phrase_embedding_queue (
	phrase_id uuid primary key references phrase (id) on delete cascade,
	queued_at timestamptz default now() not null,
	reason text not null
);

alter table public.phrase_embedding_queue owner to postgres;

comment on table public.phrase_embedding_queue is 'Queue of phrases needing embedding generation. Processed by the embed-phrase Edge Function.';

-- ============================================================================
-- Trigger functions: automatically queue phrases when data changes
-- ============================================================================
-- Queue phrase on insert or text change
create or replace function queue_phrase_for_embedding () returns trigger language plpgsql security definer as $$
BEGIN
  INSERT INTO phrase_embedding_queue (phrase_id, reason)
  VALUES (NEW.id, 'phrase_' || TG_OP)
  ON CONFLICT (phrase_id) DO UPDATE SET
    queued_at = now(),
    reason = 'phrase_' || TG_OP;
  RETURN NEW;
END;
$$;

-- Queue phrase when a translation changes
create or replace function queue_phrase_embedding_for_translation () returns trigger language plpgsql security definer as $$
DECLARE
  target_phrase_id uuid;
BEGIN
  -- Use NEW for INSERT/UPDATE, OLD for DELETE
  target_phrase_id := COALESCE(NEW.phrase_id, OLD.phrase_id);

  INSERT INTO phrase_embedding_queue (phrase_id, reason)
  VALUES (target_phrase_id, 'translation_' || TG_OP)
  ON CONFLICT (phrase_id) DO UPDATE SET
    queued_at = now(),
    reason = 'translation_' || TG_OP;

  RETURN COALESCE(NEW, OLD);
END;
$$;

-- Queue phrase when a tag changes
create or replace function queue_phrase_embedding_for_tag () returns trigger language plpgsql security definer as $$
DECLARE
  target_phrase_id uuid;
BEGIN
  target_phrase_id := COALESCE(NEW.phrase_id, OLD.phrase_id);

  INSERT INTO phrase_embedding_queue (phrase_id, reason)
  VALUES (target_phrase_id, 'tag_' || TG_OP)
  ON CONFLICT (phrase_id) DO UPDATE SET
    queued_at = now(),
    reason = 'tag_' || TG_OP;

  RETURN COALESCE(NEW, OLD);
END;
$$;

-- ============================================================================
-- Triggers on phrase, phrase_translation, phrase_tag
-- ============================================================================
create trigger queue_embedding_on_phrase_change
after insert
or
update of text,
text_script on phrase for each row
execute function queue_phrase_for_embedding ();

create trigger queue_embedding_on_translation_change
after insert
or
update
or delete on phrase_translation for each row
execute function queue_phrase_embedding_for_translation ();

create trigger queue_embedding_on_tag_change
after insert
or delete on phrase_tag for each row
execute function queue_phrase_embedding_for_tag ();

-- ============================================================================
-- RLS: embedding_config is readable by all, writable by service_role only
-- ============================================================================
alter table public.embedding_config enable row level security;

create policy "Anyone can read embedding config" on public.embedding_config for
select
	using (true);

-- ============================================================================
-- RLS: phrase_embedding is readable by all, writable by service_role only
-- ============================================================================
alter table public.phrase_embedding enable row level security;

create policy "Anyone can read phrase embeddings" on public.phrase_embedding for
select
	using (true);

-- ============================================================================
-- RLS: phrase_embedding_queue is managed by service_role (triggers use SECURITY DEFINER)
-- ============================================================================
alter table public.phrase_embedding_queue enable row level security;

-- ============================================================================
-- Grants
-- ============================================================================
grant
select
	on public.embedding_config to authenticated,
	anon;

grant all on public.embedding_config to service_role;

grant
select
	on public.phrase_embedding to authenticated,
	anon;

grant all on public.phrase_embedding to service_role;

grant all on public.phrase_embedding_queue to service_role;
